- name: Restart firewalld
  become: true
  ansible.builtin.command: "{{ item }}"
  with_items:
    - systemctl stop firewalld
    - systemctl start firewalld

- name: Restart nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Restart systemd-resolved
  become: true
  ansible.builtin.command: "{{ item }}"
  with_items:
    - systemctl restart systemd-resolved
