# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    fragments: ~
    http_method_override: false
    handle_all_throwables: true
    secret: '%env(APP_SECRET)%'
    annotations:
        enabled: false
    property_info:
        with_constructor_extractor: true
    assets:
        json_manifest_path: '%kernel.project_dir%/public/dist/manifest.json'
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id:  null
        name:        TLDID
        cookie_httponly: true
        cookie_secure: auto
        cookie_samesite: none
        storage_factory_id: session.storage.factory.native
        cookie_lifetime: '%env(TOKEN_LIFETIME)%'
    #esi: true
    #fragments: true
    php_errors:
        log: true
