<?php
/**
 *    form object classes
 *
 * @package FormsAndReports
 * @desc All classes related to the forms and reports are kept in this file
 * @access public
 * @author Graham K.L. Fong <graham.fong@tld-america.com>
 * @copyright TLD
 */

/**
 * Need these functions
 */
include_once('HTML/QuickForm.php');
include_once 'Image/Barcode2.php';
require_once 'Spreadsheet/Excel/Writer.php';


/**
 *    Base class for all forms and report classes
 *
 *  All forms and report classes extend from this class and inherit vital info
 *  like the location of the smarty template
 *
 * @package FormsAndReports
 */
class basicFormsAndReports
{
	public $itsTPLPath = 'forms_and_reports';

	//returns the html output after parsing with smarty
	function fetch()
	{
		return;
	}

	//all templates for html forms and objects are in the shared_php_inc folder
	function getSmarty()
	{
		return tldUtils::getSmarty('common');
	}

	//creates an array containing an index of the first characters in rows
	//fields, array containing fields to index
	function createIndex($rows, $field)
	{
		if (count($rows) === 0) {
			return;
		}
		$result = [];
		foreach ($rows as $row) {
			$value = trim(($row[$field] ?? ''));
			if (!in_array($value, $result, true)) {
				$result[] = $value;
			}
		}
		sort($result);
		return $result;
	}

	//returns an index to the same URI
	function fetchIndex($index, $suffix = '')
	{
		$smarty = $this->getSmarty();
		$smarty->assign('index', $index);
		$smarty->assign('suffix', $suffix);
		return $smarty->fetch('forms_and_reports/createIndex.tpl');
	}
}

/**
 *    Associative Array table
 *
 *  Creates a table from an indexed array of associative arrays
 *  like from tldUtils::getSqlToAssocArray() and an associative array of key/value
 *  pairs with the key being field name and the value being the column title.
 *
 * <code>
 * $form = new tldAssocTable( $data,
 *                                array("id"=>"ID","name"=>"Customer Name"),
 *                                $options
 *                            );
 * </code>
 *
 * options is an assoc array:
 * "plain": no colours
 * "no_table": write each line like "key: value", writes as table by default
 *
 * @package FormsAndReports
 */
class tldAssocTable extends basicFormsAndReports
{
    public $itsFields;
    public $itsData;
    public $itsOptions;

    function __construct($data, $fields, $options = [])
	{
		$this->itsFields = $fields;
		$this->itsData = $data;
		$this->itsOptions = $options;
	}

	/**
	 * return the Associative Array Report
	 *
	 * @return string
	 */
	function fetch()
	{
		$smarty = $this->getSmarty();
		$smarty->assign('data', $this->itsData);
		$smarty->assign('fields', $this->itsFields);
		$smarty->assign('options', $this->itsOptions);
		$smarty->assign('title', $this->itsOptions['title'] ?? '');
		return $smarty->fetch($this->itsTPLPath . '/tldAssocTable.tpl');
	}
}


/**
 *    HTML Table Matrix
 *
 *  Creates a table from an indexed array of associative arrays
 *  like from tldUtils::getSqlToAssocArray() and two associative arrays of key/value
 *  pairs with the key being field name and the value being the X row or Y column titles.
 *  Typically used to display COUNT values from a dataset
 *
 * @param array $options
 *        [xItems] array of string fixed list instead of autogenerated
 *        [yItems] array of string fixed list instead of autogenerated
 *      [xFieldLink] string The field on which the link has to be generated for in the column ($x=...)
 *      [yFieldLink] string The field on which the link has to be generated for in the line ($y=...)
 *        [doNotShowTotals] boolean
 *        [doNotShowXTotals] boolean
 *        [doNotShowYTotals] boolean
 *        [doNotFormatCells] boolean
 *        [xItemsReversed] boolean
 *    [yItemsReversed] boolean
 *    [style]
 *        [xItems] array of xItem with associated string style values
 *        [yItems] array of yItem with associated string style values
 *
 * @package FormsAndReports
 */
class tldMatrix extends basicFormsAndReports
{
	public $itsTitle;
	public $itsData;
	private $itsXField;
	private $itsYField;
	private $itsCellField;
	private $itsURL;
	private $itsOptions;

	public function __construct($data, $xField, $yField, $cellField, $url, $title = '', $options = [])
	{
		$this->itsTitle = $title;
		$this->itsData = $data;
		$this->itsXField = $xField;
		$this->itsYField = $yField;
		$this->itsCellField = $cellField;
		$this->itsURL = $url;
		if (isset($options['doNotShowTotals']) && $options['doNotShowTotals'] == true) {
			$options['doNotShowXTotals'] = true;
			$options['doNotShowYTotals'] = true;
		}
		$this->itsOptions = $options;
	}

	/**
	 * return the Matrix Report
	 *
	 * @return string
	 */
	function fetch()
	{
		$xItems = [];
		$yItems = [];

		$smarty = $this->getSmarty();
		$smarty->assign('title', $this->itsTitle);

		if (!count($this->itsData ?? [])) {
			return $smarty->fetch($this->itsTPLPath . '/tldMatrix.tpl');
		}
		$totals = [];
		foreach ($this->itsData as $row) {
			//get distinct headings
			if (!in_array($row[$this->itsXField], $xItems, true)) {
				$xItems[] = $row[$this->itsXField];
				if (isset($this->itsOptions['xFieldLink']) && $this->itsOptions['xFieldLink'] == true) {
					$xItemsLinks[$row[$this->itsXField]] = $row[$this->itsOptions['xFieldLink']];
				}
			}
			if (!in_array($row[$this->itsYField], $yItems, true)) {
				$yItems[] = $row[$this->itsYField];
				if (isset($this->itsOptions['yFieldLink']) && $this->itsOptions['yFieldLink'] == true) {
					$yItemsLinks[$row[$this->itsYField]] = $row[$this->itsOptions['yFieldLink']];
				}
			}
			//populate matrix
			if (isset($this->itsOptions['decimals']) && $this->itsOptions['decimals'] == true) {
				$data[$row[$this->itsXField]][$row[$this->itsYField]] =
					$this->itsOptions['doNotFormatCells'] == true ? $row[$this->itsCellField]
						: number_format($row[$this->itsCellField], 1, '.', '');
			} else {
				$data[$row[$this->itsXField]][$row[$this->itsYField]] =
					(isset($this->itsOptions['doNotFormatCells']) && $this->itsOptions['doNotFormatCells'] == true) ? $row[$this->itsCellField]
						: number_format($row[$this->itsCellField]);
			}
			//calc axis totals
			$totals['Total'][$row[$this->itsXField]] = isset($totals['Total'][$row[$this->itsXField]]) ? $totals['Total'][$row[$this->itsXField]] : 0;
			$totals['Total'][$row[$this->itsXField]] += $row[$this->itsCellField];
			$totals[$row[$this->itsYField]]['Total'] = isset($totals[$row[$this->itsYField]]['Total']) ? $totals[$row[$this->itsYField]]['Total'] : 0;
			$totals[$row[$this->itsYField]]['Total'] += $row[$this->itsCellField];
			//calc grand total
			$totals['Total']['Total'] = isset($totals['Total']['Total']) ? $totals['Total']['Total'] : 0;
			$totals['Total']['Total'] += $row[$this->itsCellField];
			if (isset($this->itsOptions['average_margin_sa2']) && $this->itsOptions['average_margin_sa2'] == true) {
				$totals['Total1'][$row[$this->itsXField]] += $row['total_marg'];
				$totals['Total2'][$row[$this->itsXField]] += $row['total_net'];
				$totals[$row[$this->itsYField]]['Total1'] += $row['total_marg'];
				$totals[$row[$this->itsYField]]['Total2'] += $row['total_net'];
				$totals['Total']['Total1'] += $row['total_marg'];
				$totals['Total']['Total2'] += $row['total_net'];
			}

		}
		if (isset($this->itsOptions['average_margin_sa2']) && $this->itsOptions['average_margin_sa2'] == true) {
			foreach ($xItems as $xItem) {
				$totals['Total'][$xItem] = 0 !== $totals['Total2'][$xItem]
                    ? $totals['Total1'][$xItem] * 100 / $totals['Total2'][$xItem]
                    : 0
                ;
			}
			foreach ($yItems as $yItem) {
				$totals[$yItem]['Total'] = $totals[$yItem]['Total1'] * 100 / $totals[$yItem]['Total2'];
			}
			$totals['Total']['Total'] = $totals['Total']['Total1'] * 100 / $totals['Total']['Total2'];
		}
		//format the numbers
		if (isset($this->itsOptions['decimals']) && $this->itsOptions['decimals'] == true) {
			foreach ($xItems as $xItem) {
				$totals['Total'][$xItem] = number_format($totals['Total'][$xItem], 1, '.', '');
			}
			foreach ($yItems as $yItem) {
				$totals[$yItem]['Total'] = number_format($totals[$yItem]['Total'], 1, '.', '');
			}
			$totals['Total']['Total'] = number_format($totals['Total']['Total'], 1, '.', '');
		} else {
			foreach ($xItems as $xItem) {
				$totals['Total'][$xItem] = number_format($totals['Total'][$xItem]);
			}
			foreach ($yItems as $yItem) {
				$totals[$yItem]['Total'] = number_format($totals[$yItem]['Total']);
			}
			$totals['Total']['Total'] = number_format($totals['Total']['Total']);
		}
		if (isset($this->itsOptions['xItems']) && $this->itsOptions['xItems']) {
			$xItems = $this->itsOptions['xItems'];
		} else {
			if (isset($this->itsOptions['xItemsRawOrder']) && $this->itsOptions['xItemsRawOrder']) {
				// Do no reorder
			} elseif (isset($this->itsOptions['xItemsReversed']) && $this->itsOptions['xItemsReversed']) {
				rsort($xItems);
			} else {
				sort($xItems);
			}
		}
		if (isset($this->itsOptions['yItems']) && $this->itsOptions['yItems']) {
			$yItems = $this->itsOptions['yItems'];
		} else {
			if (isset($this->itsOptions['yItemsRawOrder']) && $this->itsOptions['yItemsRawOrder']) {
				// Do no reorder
			} elseif (isset($this->itsOptions['yItemsReversed']) && $this->itsOptions['yItemsReversed']) {
				rsort($yItems);
			} else {
				sort($yItems);
			}
		}
		$xItemsLinks = empty($xItemsLinks) ? array_combine($xItems, $xItems) : $xItemsLinks;
		$yItemsLinks = empty($yItemsLinks) ? array_combine($yItems, $yItems) : $yItemsLinks;
		$smarty->assign('xItems', $xItems);
		$smarty->assign('yItems', $yItems);
		$smarty->assign('xItemsLink', $xItemsLinks);
		$smarty->assign('yItemsLink', $yItemsLinks);
		$smarty->assign('data', $data);
		$smarty->assign('options', $this->itsOptions);
		$smarty->assign('url', $this->itsURL);
		$smarty->assign('totals', $totals);
		return $smarty->fetch($this->itsTPLPath . '/tldMatrix.tpl');
	}
}

/**
 *    Generates a columnar report from array of data
 *
 *  IMPORTANT NOTE :  By default, Report columnar use the sorttable js library
 *  If, for any reason, we decide to stop using it, delete the class of the columnar tlp file
 *  and delete the line that include the js file "/inc/sortable.js" on intranet.tpl
 *
 * <code>
 * $report = new tldReportColumnar($erp->searchAltPN($pn), $OPTIONS);
 * $OPTIONS (array) :
 *        "xItems" => array("t_item"=>"TLD PN",
 *                          "t_suno"=>"Supplier ID",
 *                          "t_aitc"=>"Alt PN",
 *                          "t_matc"=>"Cost"),
 *        "title"  => "Title",
 *        "showzero"          => TRUE,  to show zero on cells
 *        "showNumberOfRows"  => TRUE,  to show total of data rows
 *        "sortable"          => FALSE, to unuse sorttable librarie and display tip
 *        "showItemNumbers"   => TRUE or reversed, to show sequential number in first column
 *        "stickyHeader"      => TRUE,  to set a fixed header while scrolling the table
 *
 *        "sumTotalsArray"    => array("t_matc"    columns array to show the summed total in the TFOOT ),
 *
 *        "links"             => array("t_item"=>"urltonextpage","confirmPopup"=>"Msg text on popup"),
 *          OR
 *        "links"             => array("t_item"=>array("url"=>"urltonextpage","params"=>array("par1"=>"val1","par2"=>"var2")));
 *
 *      "functions"=>array(
 *           "Delete"=>array(
 *               "url"=>"$php_self?m[0]=parts&m[1]=fav&m[2]=delConf&id=",
 *               "param"=>"id"
 *               ),
 *           "Add"=>array(
 *               "img"=>"/shared/path_icon_add",
 *               "url"=>"$php_self?m[0]=parts&m[1]=search&qty=1&pn=",
 *               "param"=>"fav_pn",
 *               "bypassDisplay" => static function ($params, $lineValues) {
 *                  return empty($lineValues['t_txta']);
 *                }
 *           )
 *      )
 * </code>
 *
 * @package FormsAndReports
 */
class tldReportColumnar extends basicFormsAndReports
{
	private $itsData;
	private $itsOptions;

	public function __construct($data, $options = [])
	{
		$this->itsData = $data;
		$this->itsOptions = $options;
	}

	/**
	 * return the Columnar Report
	 *
	 * @return string
	 */
	public function fetch()
	{
		$smarty = $this->getSmarty();
		if ($this->itsData instanceof tldPagination) {
			$data = $this->itsData->getData();
			$this->itsOptions['is_pagination'] = true;
			$this->itsOptions['sortable'] = true;
			$smarty->assign('pagination', $this->itsData);
		} elseif (isset($this->itsOptions['objects'])) {
			foreach ($this->itsData as $line) {
				$data[] = (array)$line;
			}

		} else {
			$data = $this->itsData;
		}
		$smarty->assign('data', $data ?? []);
		$smarty->assign('options', $this->itsOptions);
		return $smarty->fetch($this->itsTPLPath . '/tldReportColumnar.tpl');
	}
}

/**
 *    Generates a CSV from array of data
 *
 * <code>
 * $report = new tldCSV($erp->searchAltPN($pn),
 *                        array("xItems"=>array(    "t_item"=>"TLD PN",
 *                                        "t_suno"=>"Supplier ID",
 *                                        "t_aitc"=>"Alt PN"
 *                                        ),
 *                        "showTitles"=>true
 *                                )
 *                    );
 *
 * </code>
 *
 * @package FormsAndReports
 */
class tldCSV extends basicFormsAndReports
{
	public $itsData;
	public $itsOptions;

	function __construct($data, $options = '')
	{
		$this->itsData = $data;
		$this->itsOptions = $options;
	}

	function str_from_unicode($str, $out_charset = 'gbk')
	{
		$str = preg_replace_callback('|&#([0-9]{1,5});|', 'tldXLS::unicode2utf8_', $str);
		$str = iconv('UTF-8', $out_charset, $str);
		return $str;
	}

	function unicode2utf8_($c)
	{
		return $this->unicode2utf8($c[1]);
	}

	function unicode2utf8($c)
	{
		$str = '';
		if ($c < 0x80) {
			$str .= $c;
		} else {
			if ($c < 0x800) {
				$str .= chr(0xC0 | $c >> 6);
				$str .= chr(0x80 | $c & 0x3F);
			} else {
				if ($c < 0x10000) {
					$str .= chr(0xE0 | $c >> 12);
					$str .= chr(0x80 | $c >> 6 & 0x3F);
					$str .= chr(0x80 | $c & 0x3F);
				} else {
					if ($c < 0x200000) {
						$str .= chr(0xF0 | $c >> 18);
						$str .= chr(0x80 | $c >> 12 & 0x3F);
						$str .= chr(0x80 | $c >> 6 & 0x3F);
						$str .= chr(0x80 | $c & 0x3F);
					}
				}
			}
		}
		return $str;
	}

	/**
	 * return the CSV Report
	 *
	 * @return string
	 */
	public function fetch()
	{
		$result = '"sep=,"' . "\r\n";

		if (count($this->itsData ?? []) === 0) {
			return '';
		}
		$xItems = $this->itsOptions['xItems'];

		if ($this->itsOptions['showTitles']) {
			$resultLine = '';
			foreach ($xItems as $fieldName => $fieldTitle) {
				$resultLine .= '"' . $fieldTitle . '",';
			}
			$result .= substr($resultLine, 0, -1) . "\r\n";
		}
		if (is_array($xItems)) {
			foreach ($this->itsData as $line) {
				$resultLine = '';
				foreach ($xItems as $fieldName => $fieldTitle) {
					$resultLine .= sprintf('"%s",', $this->clean($line[is_numeric($fieldName) ? $fieldTitle : $fieldName]));
				}
				$result .= substr($resultLine, 0, -1). "\r\n";
			}
		} else {
			foreach ($this->itsData as $line) {
				$resultLine = '';
				foreach ($line as $item) {
					$resultLine .= sprintf('"%s",',$this->clean($item));
				}
				$result .= substr($resultLine, 0, -1). "\r\n";
			}
		}

		return $result;
	}

	public function save($destinationFilepath)
	{
		return (bool) file_put_contents($destinationFilepath, $this->fetch());
	}


	private function clean($a)
	{
		// Clean some special chars
		$badChars = ["\n", "\r\n", "\r", '"'];
		$data = str_replace($badChars, '', $a ?? '');
		// clean slashes
		$data = stripslashes($data);
		// Make sure to set data in UTf-8
		$data = tldXLS::str2utf8($data);
		// In case there is html entities...
		$data = tldXLS::htmlEntityDecode($data);
		// done
		return $data;
	}

	function out($filename = 'data.csv')
	{
		header('Content-Type: application/csv');
		header("Content-Disposition: attachment; filename=\"$filename\"");
		header('Pragma: public');
		header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
		echo $this->fetch();
	}
}


class tldXLS
{

	public $itsData;
	public $itsOptions;
	public $objPHPExcel;

	public function __construct($data, $options = [])
	{
		$this->itsData = $data;
		$this->itsOptions = $options;
		$this->init();
		$this->setLines();
	}

	public function init()
	{
		require_once 'PHPExcel.php';
		$this->objPHPExcel = new PHPExcel();
		if (isset($this->itsOptions['creator']) && !empty($this->itsOptions['creator'])) {
			$this->objPHPExcel->getProperties()->setCreator($this->itsOptions['creator']);
		}
		if (isset($this->itsOptions['title']) && !empty($this->itsOptions['title'])) {
			$this->objPHPExcel->getProperties()->setTitle($this->itsOptions['title']);
		}
		if (!array_key_exists('xItems', $this->itsOptions) && !empty($this->itsData[0])) {
			$this->itsOptions['xItems'] = array_combine(array_keys($this->itsData[0]), array_keys($this->itsData[0]));
		}
		$this->objPHPExcel->setActiveSheetIndex(0);
	}

	public function save($destinationFilepath)
	{
		$objWriter = PHPExcel_IOFactory::createWriter($this->objPHPExcel, 'Excel5');
		$objWriter->save($destinationFilepath);
	}

	public function out($filename = 'data.xlsx')
	{
		$objWriter = PHPExcel_IOFactory::createWriter($this->objPHPExcel, 'Excel2007');
		header('Content-Type: application/vnd.ms-excel');
		header('Content-Disposition: attachment;filename="' . $filename . '"');
		header('Cache-Control: max-age=0');
		$objWriter->save('php://output');
		return;
	}

	public function setLines()
	{
		$line = 1;
		// set titles if applicable
		if (isset($this->itsOptions['showTitles']) && !empty($this->itsOptions['showTitles'])) {
			$this->setLine($line, $this->itsOptions['xItems']);
			$line++;
		}
		// set data content
		foreach ($this->itsData as $k => $lineData) {
			// if xItems are set, use data with same order as xItems
			if (isset($this->itsOptions['xItems']) && is_array($this->itsOptions['xItems']) && !empty($this->itsOptions['xItems'])) {
				$data = [];
				foreach ($this->itsOptions['xItems'] as $key => $val) {
					// check if index xItems exists...
					if (!isset($lineData[$key])) {
						//  if not simulate empty val
						$data[$key] = '';
						continue;
					}
					$data[$key] = $lineData[$key];
				}
				$lineData = $data;
			}
			// create line
			$this->setLine($line, $lineData);
			$line++;
		}
	}

	public function setLine($lineNumber, $lineData)
	{
		$col = 0;
		foreach ($lineData as $key => $val) {
			$this->setCell($lineNumber, $col, $val);
			$col++;
		}
		return;
	}

	public function setCell($lineNumber, $columnNumber, $data)
	{
		global $user;
		// Check formatting data if applicable
		$formating = '';
		// -- case of date
		if ($user instanceof \tldUser) {
			$domain = $user->getDomain();
		} else {
			$domain = null;
		}

		if (!is_array($data) && preg_match("/^\d{4}-\d{2}-\d{2}$/", $data) && $domain === 'tld-europe.com') {
			$dtArray = explode('-', trim($data));
			// transform to excel date if applicable
			if ($data == '0000-00-00') {
				$data = '';
			} else {
				$data = PHPExcel_Shared_Date::FormattedPHPToExcel($dtArray[0], $dtArray[1], $dtArray[2]);
				$formating = 'FORMAT_DATE_DMYSLASH';
			}
		}

		if(!is_numeric($data) || (is_numeric($data) && strlen($data) > 10)){
			$formating = 'TYPE_STRING';
		}

		// Make sure to set data in UTf-8
		$data = self::str2utf8($data);
		// In case there is html entities...
		$data = self::htmlEntityDecode($data);

		// Look for style formatting
		switch ($formating) {
			case 'FORMAT_DATE_DMYSLASH':
				// update style and formatting
				$this->objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow($columnNumber, $lineNumber, $data);
				$this->objPHPExcel->getActiveSheet()
					->getStyleByColumnAndRow($columnNumber, $lineNumber)
					->getNumberFormat()
					->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_DATE_DMYSLASH);
				break;
			case 'TYPE_STRING':
				$this->objPHPExcel
					->getActiveSheet()
					->setCellValueExplicitByColumnAndRow($columnNumber, $lineNumber, $data, PHPExcel_Cell_DataType::TYPE_STRING);
				break;
			default:
				$this->objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow($columnNumber, $lineNumber, $data);
				break;
		}
		return;
	}

	public static function htmlEntityDecode($str)
	{
		return html_entity_decode($str, ENT_COMPAT | ENT_HTML401, 'UTF-8');
	}

	public static function str2utf8($str)
	{
		$possibleEncodingList = ['UTF-8', 'ISO-8859-1', 'CP936'];
		$encodingDetected = mb_detect_encoding($str, $possibleEncodingList, true);
		// if encoding detected, convert to utf8
		if ($encodingDetected !== 'UTF-8' && $encodingDetected !== false) {
			$str = iconv($encodingDetected, 'UTF-8', $str);
		}
		return $str;
	}

}

/**
 * Generates a multi level report
 *
 * <code>
 *  EXAMPLE:
 *
 *        $form = new tldReportMultiLevel(tldUtils::getSqlToAssocArray($query),
 *                        array("product_type","model"),
 *                        array(    "id"        =>"Demerit#",
 *                                "status"    =>"Status",
 *                                "date"        =>"Date",
 *                                "log_id"    =>"Log",
 *                                "short_desc"=>"Description"
 *                        ),
 *                        array(    "passField"=>"id",
 *                                "title"=>"Demerits by TYPE, MODEL",
 *                                "url"=>"$php_self?m[0]=",
 *                                "showNumberOfRowsByLevel"=>array(1),            // Will give the number of rows for the level 1, which means the model here
 *                                "links"=>array(
 *                                    "log_id"=>"$php_self?m[0]=log&id="            // list of link for each rows
 *                                ),
 *                              "menu_suffix" => "Ca suffixe maintenant !"
 *                            or
 *                                "links"=>array(
 *                                    "log_id"=>array(
 *                                        "$php_self?m[0]=log",                    // url to go
 *                                        "params"=>array("id"=>$id),                // when params needed
 *                                        "linkOptions"=>'Onclick="alert();"'),    // put any option tag
 *                                    ),
 *                                "showNumberOfRows"=>true
 *                            )
 *        );
 *
 * </code>
 * @package FormsAndReports
 */
class tldReportMultiLevel extends basicFormsAndReports
{
	public $itsTitle;
	public $itsData;
	public $itsFields;
	public $itsOptions;

	function __construct($data, $fields, $columns, $options = '')
	{
		$this->itsData = $data;            //array of data rows
		$this->itsFields = $fields;        //fields to split on
		$this->itsColumns = $columns;    //columns to display at last level
		$this->itsOptions = $options;
	}

	/**
	 * return the MultiLevel Report
	 *
	 * @return string
	 */
	function fetch()
	{
		$result = '<h3>' . $this->itsOptions['title'] . '</h3>';
		//get the table
		$suffix = isset($this->itsOptions['menu_suffix']) ? $this->itsOptions['menu_suffix'] : '';
		$table = $this->groupRec($this->itsData, $this->itsFields, 0, $suffix);

		//if nothing in $table then don't even print the header!!
		if (empty($table)) {
			$result .= '<p>No results found...</p>';
			return $result;
		}

		// Form for quick access in listing using first field
		$result .= $this->fetchIndex($this->createIndex($this->itsData, $this->itsFields[0]), $suffix) . '';

		$result .= '<table width="100%">';
		$result .= '<tr bgcolor="#d0d0d0"><td>&nbsp;</td>';
		foreach ($this->itsColumns as $key => $label) {
			$result .= "<th>{$label}</th>";
		}
		$functions = isset($this->itsOptions['functions']) ? $this->itsOptions['functions'] : [];
		foreach ($functions as $header => $values) {
			$result .= "<th style=\"text-align: center\">{$header}</th>";
		}
		$result .= '</tr>';
		$result .= $table;
		$result .= '&nbsp;</tr></table>';
		if (!empty($this->itsOptions['showGrandTotalRows'])) {
			$result .= '<b>Total rows=' . count($this->itsData) . '</b>';
		}
		return $result;
	}

	function groupRec($rows, $fields, $level = 0, $suffix = '')
	{
		$smarty = $this->getSmarty();
		if ($level >= count($fields ?? [])) {
			$smarty->assign('rows', $rows);
			$smarty->assign('columns', $this->itsColumns);
			$smarty->assign('options', $this->itsOptions);
			$smarty->assign('level', $level);
			return '</td></tr>' . $smarty->fetch($this->itsTPLPath . '/tldReportMultiLevel.tpl') .
				'<tr><td colspan="' . (count($this->itsColumns) + 1) . '">';
		}
		if (count($rows ?? [])) {
			foreach ($rows as $row) {
				$data[$row[$fields[$level]]][] = $row;
			}
			$result = '';
			foreach ($data as $key => $value) {
				if ($level == 0) {
					$keyParsed = trim($key);
					$result .= '<tr><td colspan="' . (count($this->itsColumns) + 1) . "\"><a id=\"{$keyParsed}{$suffix}\" name=\"$keyParsed\"><b>$keyParsed</b></a>";
					if (!empty($this->itsOptions['showNumberOfRowsByLevel'])) {
						if (in_array($level, $this->itsOptions['showNumberOfRowsByLevel'])) {
							$result .= ' - Total of ' . count($value) . ' rows';
						}
					}
					$result .= '<br>';
				} else {
					for ($i = 0; $i < $level; $i++) {
						$result .= '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
					}
					$result .= "<b>$key";
					if (!empty($this->itsOptions['showNumberOfRowsByLevel'])) {
						if (in_array($level, $this->itsOptions['showNumberOfRowsByLevel'])) {
							$result .= ' - Total of ' . count($value) . ' rows';
						}
					}
					$result .= '</b><br>';
				}
				$result .= $this->groupRec($value, $fields, $level + 1, $suffix);
			}
		}
		return $result ?? [];
	}
}

/**
 * Creates a vertical list of links from var $list. Each item on a separate line
 *
 * item1
 * item2
 * item3
 *
 * $fields, either key=>value pairs or array specifying which fields to use
 * $NEXT_STEP, URL to send key value to
 * EXAMPLE
 *
 * <code>
 * $form = new tldHTMLList($parts,
 *             array(    "key"=>array("erp"=>"erp","item"=>"part_number"),
 *                    "value"=>array("erp","part_number")),
 *             "/en/private/manufacturing/eng/dev.php?m[0]=avail&m[1]=view",
 *             array("title"=>"Select part number to see stock availability")
 *            );
 * </code>
 * @package FormsAndReports
 */
class tldHTMLList extends basicFormsAndReports
{
	public $itsList;
	public $itsFields;
	public $itsNEXT_STEP;

	//list, array of array of dataset rows
	//fields, array or array of arays of fieldnames to take from list array
	//NEXT_STEP, url to send keys to
	function __construct($list, $fields, $NEXT_STEP, $options = '')
	{
		$this->itsList = $list;
		$this->itsFields = $fields;
		$this->itsNEXT_STEP = $NEXT_STEP;
		$this->itsOptions = $options;
	}

	function fetch()
	{
		$smarty = $this->getSmarty();
		$smarty->assign('list', $this->itsList);
		$smarty->assign('fields', $this->itsFields);
		$smarty->assign('NEXT_STEP', $this->itsNEXT_STEP);
		$smarty->assign('options', $this->itsOptions);
		return $smarty->fetch($this->itsTPLPath . '/tldHTMLList.tpl');
	}
}

/**
 * returns a table populated with contents of input array, like a calendar/catalogue
 * <code>
 *    $report = new tldHTMLTable($cells,
 *                array(    "cols"=>2,
 *                        "attribs"=>array("table"=>" width='100%'",
 *                                        "tr"=>" bgcolor='#FFFFFF'"),
 *                        "title"=>"Title text"
 *                )
 *            );
 * </code>
 * @return string
 * @package FormsAndReports
 */
class tldHTMLTable extends basicFormsAndReports
{
	private $itsList;
	private $itsOptions;

	//list, array of array of dataset rows
	//fields, array or array of arrays of fieldnames to take from list array
	//NEXT_STEP, url to send keys to

	function __construct($list, $options)
	{
		$this->itsList = $list;
		$this->itsOptions = $options + ['cols' => 0, 'attribs' => []];
		$this->itsOptions['attribs'] = $this->itsOptions['attribs'] + ['table' => null, 'tr' => null, 'td' => null];
	}

	/**
	 * return the HTML Table
	 *
	 * @return string
	 */
	function fetch()
	{
		$smarty = $this->getSmarty();
		$smarty->assign('list', $this->itsList);
		$smarty->assign('options', $this->itsOptions);
		return $smarty->fetch($this->itsTPLPath . '/tldHTMLTable.tpl');
	}
}


/**
 * Courier form
 *
 * @package FormsAndReports
 *
 */
class tldCourier extends basicFormsAndReports
{

	public static $theAllowedCouriers = [
		'UPS', 'FED', 'DHL', 'BAX', 'EMS', 'EXAPAQ',
		'TNT', 'SUR', 'SFE', 'WAT', 'GEFCO', 'AWB', 'BOL',
	];

	function __construct($courier)
	{
		if (in_array(strtoupper($courier), self::$theAllowedCouriers)) {
			$this->itsID = strtoupper($courier);
		}
	}

	function isEmpty()
	{
		return empty($this->itsID);
	}

	public static function getList()
	{
		return self::$theAllowedCouriers;
	}

	public static function parseMultiple($text)
	{
		$lines = explode("\n", $text);
		foreach ($lines as $line) {
			if (empty($line)) {
				continue;
			}
			$data = explode('#', trim($line));
			$courier = strtoupper($data[0]);
			$trackNum = $data[1];
			if (!in_array($courier, self::$theAllowedCouriers)) {
				$courier = '';
				$trackNum = $line;
			}
			$result[] = ['courier' => $courier, 'trackNum' => $trackNum];
		}
		return $result;
	}

	public static function outMultiple($text)
	{
		$result = '';
		$lines = self::parseMultiple($text);
		if (count($lines ?? []) > 0) {
			foreach ($lines as $line) {
				$courier = new tldCourier($line['courier']);
				$result .= $courier->fetch($line['trackNum']);
			}
			return $result;
		}
	}

	function fetch($trackNum = null)
	{
		if ($this->itsID) {
			$smarty = $this->getSmarty();
			$smarty->assign('trackNum', $trackNum);
			$trackID = strtolower($this->itsID);
			return $smarty->fetch($this->itsTPLPath . '/tldCourier/' . $trackID . '.inc.tpl');
		}

		return $trackNum;
	}
}

/**
 * Class for creating a jsMenu array
 *
 * <code>
 * EXAMPLE OUTPUT: Menu1=new Array("Products","extranet.php?m[0]=products","",0,0,110);
 * </code>
 * @return string javascript code to be used in jsMenu script
 * @package FormsAndReports
 */
class tldJSMenu extends basicFormsAndReports
{
	public $itsMenu;    //array to hold menu structure

	function __construct($menu)
	{
		$this->itsMenu = $menu;
	}

	function fetch()
	{
		if (!is_array($this->itsMenu)) {
			return;
		}
		$smarty = $this->getSmarty();
		$menu = '';
		$i = 1;
		foreach ($this->itsMenu as $item) {
			$this->getMenuRec($item, $i, 0, $menu);
			$i++;
		}
		$menu .= 'var NoOffFirstLineMenus=' . count($this->itsMenu) . ';';
		$smarty->assign('menuArray', $menu);
		return $smarty->fetch($this->itsTPLPath . '/tldJSMenu.tpl');
	}

	function getMenuRec($a, $i, $count, &$result)
	{
		if (!is_array($a[0])) {
			$result .= "Menu$i";
			$result .= '=new Array("' . $a[0] . '","' . $a[1] . "\",\"\",$count," . $a[2] . ',' . $a[3] . ");\n";
		} else {
			$j = 0;
			foreach ($a as $item) {
				$k = '';
				$count = '0';
				if ($j == 0) {
					$k = "$i";
					$count = count($a) - 1;
				} else {
					$k = $i . '_' . $j;
				}
				$this->getMenuRec($item, $k, $count, $result);
				$j++;
			}
		}
	}
}


class tldOverlib extends basicFormsAndReports
{

	public $itsText;

	function __construct($text, $options = '')
	{
		$this->itsText = $this->cleanText($text);
		$this->itsOptions = $options;
	}

	function cleanText($text)
	{
		// Clean line return
		$nallow = ["\r", "\n"];
		$text = str_replace($nallow, '', $text);
		// Clean html
		$text = htmlentities($text);
		// clean quotes
		$text = TldDatabase::escape($text);
		// Clean special char
		$nallow = ['>', '<'];
		$text = str_replace($nallow, '', $text);
		return $text;
	}

	/**
	 * return the "overlib" string
	 * @return string
	 */
	function fetch()
	{
		$smarty = $this->getSmarty();

		// if there is a link name specified use it, else use "Over Here"
		if ($this->itsOptions['linkName']) {
			$linkName = $this->itsOptions['linkName'];
		} else {
			$linkName = 'Over Here';
		}
		$vars = '';
		// check if the CAPTION is specified in the Options
		if ($this->itsOptions['CAPTION']) {
			$vars .= ",CAPTION,'{$this->itsOptions['CAPTION']}'";
		}

		// check if the WIDTH is specified in the Options
		if ($this->itsOptions['WIDTH']) {
			$vars .= ",WIDTH,'{$this->itsOptions['WIDTH']}'";
		} else {
			$vars .= ',WIDTH,250';
		}

		// check if the OFFSETX is specified in the Options, default "OFFSETX,50""
		if ($this->itsOptions['OFFSETX']) {
			$vars .= ",OFFSETX,'{$this->itsOptions['OFFSETX']}'";
		} else {
			$vars .= ',OFFSETX,50';
		}

		// check if the VAUTO = OFF is specified in the Options, default "VAUTO"
		if (($this->itsOptions['VAUTO'] ?? null) !== 'OFF') {
			$vars .= ',VAUTO';
		}

		// check if the FGCOLOR is specified in the Options, by default uses "FGCOLOR, '#eeeeee'"
		if ($this->itsOptions['FGCOLOR'] ?? null) {
			$vars .= ",FGCOLOR,'{$this->itsOptions['FGCOLOR']}'";
		} else {
			$vars .= ",FGCOLOR,'#eeeeee'";
		}

		// check if the BGCOLOR is specified in the Options, by default uses "BGCOLOR, 'gray'"
		if ($this->itsOptions['BGCOLOR'] ?? null) {
			$vars .= ",BGCOLOR,'{$this->itsOptions['BGCOLOR']}'";
		} else {
			$vars .= ",BGCOLOR,'gray'";
		}

		// check if the CAPCOLOR is specified in the Options by default uses "CAPCOLOR, '#dedede'"
		if ($this->itsOptions['CAPCOLOR'] ?? null) {
			$vars .= ",CAPCOLOR,'{$this->itsOptions['CAPCOLOR']}'";
		} else {
			$vars .= ",CAPCOLOR,'#dedede'";
		}

		$result = "<a href=\"javascript:void(0);\" onMouseOver=\"javascript:overlib('" . $this->itsText . "'" . $vars . ');" onMouseOut="javascript:nd();">' . $linkName . '</a>';
		return $result;
	}
}


class tldTagCloud
{
	function __construct()
	{
		$this->itsTags = [];
		$this->itsMax = 0;
		$this->itsMin = 0;
		$this->itsMinSize = 9;
		$this->itsMaxSize = 48;
	}

	function addTag($tag, $weight, $url = '')
	{
		if ($weight == 0) {
			return;
		}
		if ($weight > $this->itsMax || $this->itsMax == 0) {
			$this->itsMax = $weight;
		} elseif ($weight < $this->itsMin || $this->itsMin == 0) {
			$this->itsMin = $weight;
		}
		$this->itsTags[$tag] = [
			'weight' => $weight,
			'url' => $url,
		];
	}

	function fetch()
	{
		if (count($this->itsTags) == 0) {
			return;
		}
		$r = '';
		foreach ($this->itsTags as $tag => $row) {
			if ($this->itsMax - $this->itsMin == 0) {
				$size = $this->itsMinSize;
			} else {
				$size = floor($this->itsMinSize +
					(
						($this->itsMaxSize - $this->itsMinSize) * ($row['weight'] - $this->itsMin) /
						($this->itsMax - $this->itsMin)
					)
				);
			}
			$r .= '<a ' . (empty($row['url']) ? '' : "href='" . $row['url'] . urldecode($tag) . "' ") . "style='font-size:{$size}px'>$tag</a>";
		}
		return $r;
	}


}


/**
 * Generates a GANTT chart
 *
 * <code>
 * $options = array(
 *
 *    'title' => 'Title String Of Chart Name',
 *
 *    'links' => array(
 *        'field' => array(
 *            "url"=>"$php_self?m[0]=meap&m[1]=view",
 *            "params"=>array('m'=>array('meap','view'),'id'=>$id),
 *            "options"=>'onclick=""',
 *        ),
 *
 *        or
 *
 *        'field'=>"$php_self?m[0]=meap&m[1]=view&id=",
 *    ),
 *
 *    'sortable' => array('field1','field2'),
 *
 *    'parentAttributes' => array(
 *        ## Formatted attributes string for parent elements (TABLE,THEAD,TBODY)
 *        ## Parameter 1: $module Name Value
 *        # ~ format string explained in PHP documentation @ http://php.net/sprintf
 *        # ~ key value must be lower case
 *        'table' => 'border="1"',
 *    ),
 *
 *    'rowAttributes' => array(
 *        ## Formatted attributes string for rows in THEAD
 *        ## Parameter 1: $module Name Value
 *        # ~ format string explained in PHP documentation @ http://php.net/sprintf
 *        'thead' => 'onclick="alert(\'hello');"',
 *
 *        ## Formatted attributes string for rows in TBODY
 *        ## Parameter 1: Current Row # (starting at zero)
 *        ## Parameter 2: $module Name Value
 *        # ~ format string explained in PHP documentation @ http://php.net/sprintf
 *        'tbody' => 'onclick="alert(\'This is row #%1$d\');"',
 *    ),
 *
 *    'groupHeaders' => array(
 *        array(
 *            ## Array of $xItems keys that will be grouped together
 *            # ~ for columnSettings field defined as gantt, this already is grouped and will be ignored in this group
 *            # ~ this will change display order of columns from $xItems
 *            'columns' => array('field1','field2'),
 *
 *            ## Title shown in merged cell above the grouped column fields
 *            'title' => 'Title String Of Grouped Columns',
 *
 *            ## Formatted attributes string for the merged cell in THEAD
 *            ## Parameter 1: $module Name Value
 *            # ~ format string explained in PHP documentation @ http://php.net/sprintf
 *            'thAttributes' => 'style="background-color:#ffe;" title="This is the Group Title"',
 *        )
 *    ),
 *
 *    'groupAttributes' => array(
 *        'field' => array(
 *            ## Formatted attributes string for cells in TBODY (will overwrite matched attributes from previous cellAttributes defined in columnSettings)
 *            ## Parameter 1: $rows Value
 *            ## Parameter 2: Current Row # (starting at zero)
 *            ## Parameter 3: $module Name Value
 *            # ~ format string explained in PHP documentation @ http://php.net/sprintf
 *            # ~ this will match the $rows value with the key value
 *            'ALPHA' => 'style="background-color:#fff;"',
 *
 *            ## Default formatted attributes string for cells in TBODY (will overwrite matched attributes from previous cellAttributes defined in columnSettings)
 *            ## Parameter 1: $rows Value
 *            ## Parameter 2: Current Row # (starting at zero)
 *            ## Parameter 3: $module Name Value
 *            # ~ format string explained in PHP documentation @ http://php.net/sprintf
 *            # ~ this will be the default attribute string for unmatched $rows value (key has to be zereo)
 *            'style="background-color:#ffe;"',
 *        )
 *    ),
 *
 *    'columnSettings' => array(
 *        'field' => array(
 *            ## Type of column (text, ifactor, meter, gantt, description)
 *            # ~ default is text
 *            'type' => 'text',
 *
 *            ## Optional callback for $row value
 *            # ~ callback explained in PHP documentation @ http://php.net/manual/language.pseudo-types.php#language.types.callback
 *            'callback' => 'intval',
 *
 *            ## Formatted attributes string for cell in the THEAD
 *            ## Parameter 1: $module Name Value
 *            # ~ format string explained in PHP documentation @ http://php.net/sprintf
 *            'thAttributes' => 'style="text-align:right;"',
 *
 *            ## Formatted attributes string for cells in TBODY
 *            ## Parameter 1: $rows Value
 *            ## Parameter 2: Current Row # (starting at zero)
 *            ## Parameter 3: $module Name Value
 *            # ~ format string explained in PHP documentation @ http://php.net/sprintf
 *            'cellAttributes' => 'style="padding: 0 10px;"',
 *
 *            ## Icon selected from array in tldGanttChart.tpl.php
 *            'icon' => 'idea',
 *
 *            ## Bool value to use the defined icon as the header value in THEAD
 *            # ~ will be ignored if icon is not defined
 *            # ~ will replace the $xItems value
 *            'useIconHeader' => true,
 *
 *            ## Bool value to use the defined icon as the cell value in TBODY
 *            # ~ will be ignored if icon is not defined
 *            # ~ will replace the $rows value
 *            'useIconValue' => true,
 *
 *            ## Formatted attributes string for icon in TBODY
 *            ## Parameter 1: $rows Value
 *            ## Parameter 2: Current Row # (starting at zero)
 *            ## Parameter 3: $module Name Value
 *            # ~ format string explained in PHP documentation @ http://php.net/sprintf
 *            # ~ will be ignored if icon is not defined
 *            'imgAttributes' => 'title="ID"',
 *
 *            ## Formatted title attribute string for cell and icon in TBODY (will overwrite title attribute defined in cellAttributes and imgAttributes)
 *            ## Parameter 1: $rows Value
 *            ## Parameter 2: $module Name Value
 *            # ~ format string explained in PHP documentation @ http://php.net/sprintf
 *            'title' => 'ID #%d',
 *
 *            ## Use a title attribute in the cell that uses any $row field for it's value in TBODY (will overwrite title attribute defined in cellAttributes and title)
 *            'tdTitle' => 'field3',
 *
 *            ## Use a title attribute in the icon that uses any $row field for it's value in TBODY (will overwrite title attribute defined in imgAttributes and title)
 *            # ~ will be ignored if icon is not defined
 *            'imgTitle' => 'field3',
 *        ),
 *
 *        'field' => array(
 *            ## Type ifactor (Importance Factor)
 *            # ~ $rows value must be an integer in (1,10,100,1000,10000)
 *            'type' => 'ifactor',
 *        ),
 *
 *        'field' => array(
 *            ## Type meter (Percentage Complete)
 *            # ~ $rows value must be an integer between 0-100
 *            # ~ value will automatically be rounded to the nearest 10
 *            'type' => 'meter',
 *        ),
 *
 *        'field' => array(
 *            ## Type gantt (Project Outlook Timeframe)
 *            # ~ $rows value must be a date (or datetime) when started
 *            'type' => 'gantt',
 *
 *            ## Preview dates as day, week or month
 *            # ~ default is month
 *            'zoom' => 'day',
 *
 *            ## Field when due date is defined
 *            # ~ default is current date
 *            'due' => 'field',
 *
 *            ## Range showing the equal amount of days, weeks or months in the past and future
 *            # ~ default is 6
 *            'range' => 4,
 *
 *            ## Range showing the days, weeks or months in the past (will override range settings)
 *            # ~ zero value is today, this week or this month
 *            # ~ default is 6
 *            'rangeBack' => 3,
 *
 *            ## Range showing the days, weeks or months in the future (will override range settings)
 *            # ~ zero value is today, this week or this month
 *            # ~ default is 6
 *            'rangeForward' => 8,
 *
 *            ## Include optional subgroup header to group by year, month, week, etc
 *            'subgroup' => true,
 *
 *            ## How to group optional subgroup header (by date string format)
 *            # ~ default is Y
 *            'subgroupDateFormat' => 'o',
 *
 *            ## Optional gantt tic display format (by date string format)
 *            # ~ default is null (display numeric)
 *            'ticDateFormat' => 'M',
 *
 *            ## Optional cell value function
 *            # ~ default is &nbsp;
 *            # ~ Argument 1 is the row line
 *            # ~ Argument 2 is the unix timestamp of offset A
 *            # ~ Argument 3 is the unix timestamp of offset B
 *            'displayCallback' => function($line, $offsetA, $offsetB){
 *                return $line['id'];
 *            },
 *        )
 *    )
 * );
 * </code>
 *
 * @package FormsAndReports
 */
class tldGanttChart extends basicFormsAndReports
{
	public $itsModule;
	public $itsData;
	public $itsHeaders;
	public $itsColumns;
	public $itsOrder;
	public $itsOptions;
	public $sess;
	public $date;

	/**
	 * Constructor
	 * Class for building Gantt Chart
	 * @param string $module Module Name
	 * @param array $data Rows Data
	 * @param array $xItems Fields Mapping
	 * @param array $options Option Settings
	 * @return    object    tldGanttChart
	 */
	function __construct($module, $data, $xItems, $options = [])
	{
		global $sess;
		$this->itsModule = $module;
		$this->itsData = $data;
		$this->itsColumns = $xItems;
		$this->itsOptions = $options;
		$this->itsOrder = [];
		#$this->groupedHeaders = array();
		$this->itsHeaders = [];
		$this->date = mktime(0, 0, 0, date('m'), date('d'), date('Y'));

		if (!isset($sess[$this->itsModule]['gantt'])) {
			$sess[$this->itsModule]['gantt'] = [];
		}
		$this->sess =& $sess[$this->itsModule]['gantt'];

		$this->sort();
		$this->prepare();
	}

	/**
	 * Prepare options for chart display
	 */
	function prepare()
	{
		foreach (array_keys($this->itsColumns) AS $field) {
			// Set defaults
			if (isset($this->itsOptions['columnSettings'][$field]['type'])) {
				$settings = $this->itsOptions['columnSettings'][$field];
				switch ($this->itsOptions['columnSettings'][$field]['type']) {
					case 'gantt':
						if (isset($settings['rangeBack']) OR isset($settings['rangeForward'])) {
							$settings['rangeBack'] = (isset($settings['rangeBack'])) ? ($settings['rangeBack'] > 0) ? (int)$settings['rangeBack'] : 0 : 6;
							$settings['rangeForward'] = (isset($settings['rangeForward'])) ? ($settings['rangeForward'] > 0) ? (int)$settings['rangeForward'] : 0 : 6;
							$tics = range(-$settings['rangeBack'], +$settings['rangeForward']);
						} else {
							$settings['range'] = (isset($settings['range'])) ? ($settings['range'] > 0) ? (int)$settings['range'] : 0 : 6;
							$tics = range(-$settings['range'], +$settings['range']);
						}
						$settings['zoom'] = (in_array($settings['zoom'], ['day', 'week', 'month'])) ? $settings['zoom'] : 'month';
						foreach ($tics AS $tic) {
							$a = strtotime("$tic {$settings['zoom']}", $this->date);

							$settings['tics'][] = [
								'title' => ($settings['ticDateFormat']) ? date($settings['ticDateFormat'], $a) : $tic,
								'tic' => $tic,
							];

							switch ($settings['zoom']) {
								case 'day':
									$b = mktime(23, 59, 59, date('m', $a), date('d', $a), date('Y', $a));
									break;
								case 'week':
									$a = mktime(0, 0, 0, date('m', $a), date('d', $a) - date('N', $a) + 1, date('Y', $a));
									$b = mktime(23, 59, 59, date('m', $a), date('d', $a) + 6, date('Y', $a));
									break;
								case 'month':
									$a = mktime(0, 0, 0, date('m', $a), 1, date('Y', $a));
									$b = mktime(23, 59, 59, date('m', $a) + 1, 0, date('Y', $a));
									break;
							}
							$settings['offset'][$tic] = ['A' => $a, 'B' => $b];
							if ($settings['subgroup']) {
								$settings['subgroupDateFormat'] = $settings['subgroupDateFormat'] ? $settings['subgroupDateFormat'] : 'Y';
								$settings['subgroups'][date($settings['subgroupDateFormat'], $a)][] = $tic;
							}
						}
						break;
				}
				$this->itsOptions['columnSettings'][$field] = $settings;
			}
		}

		// PREPARE HEADER & COLUMN ORDER
		foreach ($this->itsColumns AS $field => $title) {
			if (in_array($field, $this->itsOrder)) {
				continue;
			}
			if (in_array($this->itsOptions['columnSettings'][$field]['type'], ['gantt'])) {
				$columns = [];
				foreach ((array)$this->itsOptions['columnSettings'][$field]['tics'] AS $header) {
					$columns[] = [
						'title' => $header['title'],
						'tic' => $header['tic'],
						'field' => $field,
					];
				}
				$this->itsHeaders[] = [
					'field' => $field,
					'subgrouped' => ($this->itsOptions['columnSettings'][$field]['subgroup']) ? true : false,
					'grouped' => true,
					'title' => $title,
					'attributes' => $this->itsOptions['columnSettings'][$field]['thAttributes'],
					'columns' => $columns,
				];
				$this->itsOrder[] = $field;
				continue;
			}

			foreach ((array)$this->itsOptions['groupHeaders'] AS $group) {
				if (in_array($field, (array)$group['columns'])) {
					$columns = [];
					foreach ($this->itsColumns AS $field => $header) {
						if (in_array($this->itsOptions['columnSettings'][$field]['type'], ['gantt'])) {
							continue;
						}
						if (in_array($field, (array)$group['columns']) AND !in_array($field, $this->itsOrder)) {
							$columns[] = [
								'title' => $header,
								'field' => $field,
							];
							$this->itsOrder[] = $field;
						}
					}
					$this->itsHeaders[] = [
						'field' => $field,
						'grouped' => true,
						'title' => $group['title'],
						'attributes' => $group['thAttributes'],
						'columns' => $columns,
					];
					continue 2;
				}
			}

			if (!in_array($field, $this->itsOrder)) {
				$this->itsHeaders[] = [
					'field' => $field,
					'columns' => [[
						'title' => $title,
						'field' => $field,
					]],
				];
				$this->itsOrder[] = $field;
			}
		}

		// PREPARE DATA
		if (!empty($this->itsOptions['columnSettings'])) {
			foreach ($this->itsData AS &$row) {
				foreach ($this->itsOptions['columnSettings'] AS $field => $settings) {
					if (array_key_exists($field, $row) && !empty($settings['callback'])) {
						$row[$field] = call_user_func($settings['callback'], $row[$field]);
					}
				}
			}
		}
	}

	/**
	 * Fetch html string of chart
	 * @return    string
	 */
	function fetch()
	{
		global $php_self;
		ob_start();
		include($this->itsTPLPath . '/tldGanttChart.tpl.php');
		$html = ob_get_contents();
		ob_end_clean();
		return $html;
	}

	/**
	 * Sort data list by column field, by last sort method or by REQUEST value
	 * or stored session sort field
	 * @param string $field Field name to sort
	 */
	function sort($field = null)
	{
		if ($field === null) {
			if (isset($_REQUEST['sort'])) {
				$this->sort($_REQUEST['sort']);
			} else {
				if ($this->sess['sort']) {
					usort($this->itsData, [$this, '_usort']);
				}
			}
		} elseif (array_key_exists($field, $this->itsData[0])) {
			if ($field == $this->sess['sort']) {
				$this->sess['order'] = ($this->sess['order'] === 'asc') ? 'desc' : 'asc';
			} else {
				$this->sess['sort'] = $field;
				$this->sess['order'] = 'asc';
			}
			usort($this->itsData, [$this, '_usort']);
		} else {
			// Do nothing
		}
	}

	/**
	 * Internal user method for comparing the sort order of each row
	 * @param array $a
	 * @param array $b
	 * @return    integer
	 */
	function _usort($a, $b)
	{
		if (is_numeric($a[$this->sess['sort']]) AND is_numeric($b[$this->sess['sort']])) {
			$compare = ($a[$this->sess['sort']] == $b[$this->sess['sort']]) ? 0 : (($a[$this->sess['sort']] > $b[$this->sess['sort']]) ? 1 : -1);
		} else {
			$compare = strcmp($a[$this->sess['sort']], $b[$this->sess['sort']]);
		}
		return ($this->sess['order'] === 'desc') ? -$compare : $compare;
	}

	/**
	 * Format string with escaped values
	 * @param string $string Input String
	 * @param string $replace,... unlimited OPTIONAL Replace format
	 * @return    string
	 */
	function strFormat($string)
	{
		$arguments = array_filter(array_slice(func_get_args(), 1));
        $arguments = array_map('trim', $arguments);
        return trim(vsprintf($string ?? '', $arguments));
	}

	/**
	 * Convert to html entities
	 * @param string $string Input string
	 * @param string $default Default value if input is empty
	 * @return    string
	 */
	function toHtml($string, $default = '&nbsp;')
	{
		$string = trim($string ?? '');
		return ($string != '') ? tldUtils::isohtmlspecialchars($string) : $default;
	}

	/**
	 * Merges multiple attributes into an html ready tag string
	 * @param array|string $attributes HTML Tag Attributes
	 * @param array|string $attributes,... unlimited OPTIONAL Tag attributes that will override matched attributes on the left
	 * @return    string
	 */
	function setAttributes($attributes)
	{
		$parameters = func_get_args();
		$attributes = $output = [];

		foreach ($parameters AS $param) {
			if (empty($param)) {
				continue;
			}
			if (is_string($param)) {
				$attributes = array_merge($attributes, $this->attrArray($param));
			} elseif (is_array($param)) {
				$attributes = array_merge($attributes, $param);
			}
		}
		$attributes = array_change_key_case(array_map('trim', $attributes), CASE_LOWER);
		foreach ($attributes AS $key => $value) {
			if (!empty($key)) {
				$output[trim($key)] = trim($key) . '="' . $this->toHtml($value, '') . '"';
			}
		}
		return (count($output) > 0) ? ' ' . implode(' ', $output) : '';
	}

	function attrArray($string)
	{
		$attributes = [];
		try {
			$string =  mb_convert_encoding($string, 'UTF-8', mb_list_encodings());
			$x = new SimpleXMLElement("<element $string />");
			$attr = $x->attributes();
			foreach ($attr AS $key => $value) {
				$attributes[(string)$key] = (string)$value;
			}
		} catch (Exception $e) {
		}
		return $attributes;
	}

	/**
	 * Checks if group headers exist
	 * @return    boolean
	 */
	function hasGroupHeaders()
	{
		foreach ($this->itsHeaders AS $header) {
			if ($header['grouped']) {
				return true;
			}
		}
		return false;
	}

	/**
	 * Checks if subgroup headers exist
	 * @return    boolean
	 */
	function hasSubGroupHeaders()
	{
		foreach ($this->itsHeaders AS $header) {
			if ($header['subgrouped']) {
				return true;
			}
		}
		return false;
	}

	/**
	 * Check if integer is between start and end range
	 * @param integer $integer
	 * @param integer $start
	 * @param integer $end
	 * @return    boolean
	 */
	function between($integer, $start, $end)
	{
		return ($integer >= $start AND $integer <= $end) ? true : false;
	}
}

class tldPagination extends basicFormsAndReports
{
	public $itsInstance;
	public $itsData;
	public $itsPage;
	public $itsLimit;
	public $itsDisplay;

	function __construct($instance_name, $rows, $limit = 10)
	{
		global $sess;
		$this->itsInstance =& $sess['pagination'][$instance_name];
		$this->itsData = $rows;
		$this->itsLimit = $limit;
		$this->itsPage = $this->getPage();
		$this->itsDisplay = $this->getDisplay();
		$this->itsInstance = [
			'name' => $instance_name,
			'page' => $this->itsPage,
			'show' => $this->itsDisplay,
		];
	}

	function getPage()
	{
		if (!empty($this->itsPage)) {
			return $this->itsPage;
		}
		// Set default page
		$page = 1;
		// Set page from stored session
		if ($this->itsInstance['page']) {
			$page = $this->itsInstance['page'];
		}
		// Set page number if passed in request
		if (is_numeric($_REQUEST['page'])) {
			$page = (int)$_REQUEST['page'];
		}
		// Set navigation keywords for page number
		switch ($_REQUEST['page']) {
			case 'first':
				$page = 1;
				break;
			case 'prev':
				--$page;
				break;
			case 'next':
				++$page;
				break;
			case 'last':
				$page = $this->getPageCnt();
				break;
		}
		// Only allow min/max page count
		if ($page < 1) {
			$page = 1;
		} elseif ($page > $this->getPageCnt()) {
			$page = $this->getPageCnt();
		}
		return $page;
	}

	function getDisplay()
	{
		if (!empty($this->itsDisplay)) {
			return $this->itsDisplay;
		}
		// Set default display
		$display = 'less';
		// Set display from stored session
		if ($this->itsInstance['show']) {
			$display = $this->itsInstance['show'];
		}
		// Set display from request
		switch ($_REQUEST['page']) {
			case 'all':
				$display = 'all';
				break;
			case 'less':
				$display = 'less';
				break;
		}
		return $display;
	}

	function getPageCnt()
	{
		if (!$this->getDataCnt()) {
			return 1;
		}
		$pages = $this->getDataCnt() / $this->itsLimit;
		return ceil($pages);
	}

	function getDataCnt()
	{
		return count($this->itsData);
	}

	function getData()
	{
		if ($this->itsDisplay === 'all') {
			return $this->itsData;
		}
		$chunked = [];
		$page = $line = 1;
		foreach ($this->itsData AS $value) {
			if ($page == $this->itsPage) {
				$chunked[] = $value;
			}
			if ($line % $this->itsLimit === 0) {
				$page++;
			}
			$line++;
		}
		return $chunked;
	}

	function getCntString()
	{
		if (!$this->getDataCnt()) {
			return 'No results';
		}
		if ($this->itsDisplay === 'all') {
			return '';
		}
		return "Page {$this->itsPage} of {$this->getPageCnt()} ({$this->getDataCnt()} results)";
	}

	function getNavLinks($url, $show_jumpto = true, $show_toggle = true)
	{
		$parts = explode('?', $url);
		parse_str($parts[1], $params);
		unset($params['page']);
		$url = $parts[0] . '?';
		if (count($params) > 0) {
			$url .= http_build_query($params) . '&';
		}
		$options = [
			'show_jumpto' => $show_jumpto,
			'show_toggle' => $show_toggle,
		];

		$smarty = $this->getSmarty();
		$smarty->assign('pg_url', $url);
		$smarty->assign('pg_options', $options);
		$smarty->assign('pg_object', $this);
		return $smarty->fetch($this->itsTPLPath . '/tldPagination.tpl');
	}
}

/**
 * Class for handling and manipulating organisation chart form
 * @param $options array
 *     link -> url of the form action
 *     title -> title of the form
 * @package FormsAndReports
 */
class tldOrgSelectionForm extends basicFormsAndReports
{

	public $itsOptions;

	function __construct($options = [])
	{
		$this->itsOptions = $options;
	}

	function validate()
	{
		global $_POST;
		return $_POST['frmSubmit'] ?? null;
	}

	function toHTML()
	{
		return $this->fetch();
	}

	function fetch()
	{
		$_FORM_OPTIONS = $this->itsOptions;
		return include($this->itsTPLPath . '/tldOrgSelectionForm.tpl.php');
	}

	function exportValues()
	{
		global $_POST;
		if (!$this->validate()) {
			return;
		}
		return $this->getArrayFromPost($_POST);
	}

	function getOrgDimensionList()
	{
		return ['division', 'subdivision', 'region', 'bu', 'department', 'function'];
	}

	function getArrayFromPost($post)
	{
		// Dimensions
		$dimList = self::getOrgDimensionList();
		// Counting lines to add
		$nbLinesToAdd = 1;
		foreach ($dimList as $dim) {
			// if no data, add one entry NULL (id=0)
			if (empty($post[$dim])) {
				$post[$dim][] = 0;
			}
			// calculate total rules to create
			$nbLinesToAdd = $nbLinesToAdd * count($post[$dim]);
		}
		// Assigning data to lines per dimensions
		$toAdd = [];
		foreach ($post['division'] as $division) {
			foreach ($post['subdivision'] as $subdivision) {
				foreach ($post['region'] as $region) {
					foreach ($post['bu'] as $bu) {
						foreach ($post['department'] as $department) {
							foreach ($post['function'] as $function) {
								$entities = [
									'division' => $division,
									'subdivision' => $subdivision,
									'region' => $region,
									'bu' => $bu,
								];
								foreach ($entities as $type => &$value) {
									if ($type !== $post['type']) {
										$value = 0;
									}
								}
								$positions = [
									'department' => $department,
									'function' => $function,
								];

								$toAdd[] = $entities + $positions;
							}
						}
					}
				}
			}
		}

		return $toAdd;
	}

}

/**
 * Class for converting html to pdf
 * @package FormsAndReports
 *
 * More info --> http://code.google.com/p/wkhtmltopdf/
 * Manual --> http://madalgo.au.dk/~jakobt/wkhtmltoxdoc/wkhtmltopdf_0.10.0_rc2-doc.html
 *
 * <code>
 *   $OPTIONS = array(
 *      encoding    => the encoding you need (utf-8,iso-XXXXX,GBXXXXX)
 *      margin      => in mm (default 10mm)
 *      title       => string title (default none)
 *      pagesize    => A4 or Letter (default A4)
 *      orientation => Landscape or Portrait (default Portrait)
 *   );
 *
 *   Options below forced in command:
 *      --lowquality
 *      --disable-javascript
 *
 * </code>
 */
class tldHTML2PDF
{

	public $itsHtml;
	public $itsOptions;
	public $itsHtmlTempFile;
	/** @var basicFile */
	public $itsConvertedPdfFile = null;

	public function __construct($string, $options = '')
	{
		$this->itsHtml = $string;
		$this->itsOptions = $options;
		$e = $this->convert();
		if (is_string($e)) {
			error_log("tldHTML2PDF::__construct() error -> $e");
			echo $e;
		}
	}

	/**
	 * Convert HTML string into a PDF file
	 * @return string on error
	 */
	public function convert()
	{
		// Create html file
		$e = $this->createHtmlFile();
		if (is_string($e)) {
			return $e;
		}
		// Protect commands by parsing arguments
		$infile = escapeshellcmd($this->itsHtmlTempFile->getFilePath());
		$outfile = escapeshellcmd(tempnam('/tmp', 'html2pdf')) . '.pdf';
		// Look for options
		$options = null;
		// Page Margin
		$margin = '10mm';
		if (!empty($this->itsOptions['margin'])) {
			$margin = escapeshellarg($this->itsOptions['margin']);
		}
		$options = " --margin-bottom $margin --margin-left $margin --margin-right $margin --margin-top $margin";
		// Page orientation
		$orientation = 'Portrait';
		if (!empty($this->itsOptions['orientation'])) {
			$orientation = escapeshellarg($this->itsOptions['orientation']);
		}
		$options .= " --orientation $orientation";
		// Page size
		$pagesize = 'A4';
		if (!empty($this->itsOptions['pagesize'])) {
			$pagesize = escapeshellarg($this->itsOptions['pagesize']);
		}
		$options .= " --page-size $pagesize";
		// Background
		$background = ' --background';
		if (!isset($this->itsOptions['background']) || $this->itsOptions['background'] === false) {
			$background = ' --no-background';
		}
		$options .= " $background";
		// Title
		if (!empty($this->itsOptions['title'])) {
			$options .= ' --title ' . escapeshellarg($this->itsOptions['title']);
		}
		// Encoding
		if (!empty($this->itsOptions['encoding'])) {
			$options .= ' --encoding ' . escapeshellarg($this->itsOptions['encoding']);
		}

		if (!empty($this->itsOptions['footer'])) {
			$options .= ' --footer-right ' . escapeshellarg($this->itsOptions['footer']);
		}
		// Convert and create PDF file
		$exec_cmd = "/usr/local/bin/wkhtmltopdf --lowquality --disable-javascript $options $infile $outfile";
		// For local use
		//$exec_cmd = "xvfb-run -a wkhtmltopdf --lowquality --disable-javascript $options $infile $outfile";
		exec($exec_cmd, $exec_output, $exec_status);
		if ($exec_status <> 0) {
			$err = implode(', ', (array)$exec_output);
			return 'system exec() command error: ' . $err;
		}
		// assign converted file as basicFile object
		$this->itsConvertedPdfFile = new basicFile($outfile);
		return;
	}

	/**
	 * Create temp file from html string
	 * @return string on error
	 */
	private function createHtmlFile()
	{
		// create temp files
		$filename = tempnam('/tmp', 'html2pdf');
		// create basic file object
		$this->itsHtmlTempFile = new basicFile($filename);
		if (!$this->itsHtmlTempFile->isFile()) {
			return "The file $filename was not created";
		}
		// rename to have html extension (htmldoc v 1.8.27 requires it)
		$this->itsHtmlTempFile->rename(
			$this->itsHtmlTempFile->getBasename() . '.html'
		);
		$filename = $this->itsHtmlTempFile->getFilePath();
		// check if file is ok
		if (!$this->itsHtmlTempFile->isWritable()) {
			return "The file $filename is not writable";
		}
		// try to open it
		if (!$handle = fopen($filename, 'a')) {
			return "Cannot open file ($filename)";
		}
		// look for options
		// --- update http references (links)
		if (!empty($this->itsOptions['links'])) {
			$this->itsHtml = str_replace(
				$this->itsOptions['links']['baseurl'],
				$this->itsOptions['links']['basedir'],
				$this->itsHtml
			);
		}
		// write in temp file
		if (fwrite($handle, $this->itsHtml) === false) {
			return "Cannot write to file ($filename)";
		}
		// close file
		fclose($handle);
		// return
		return;
	}

	/**
	 * Get converted pdf file object
	 * @return basicFile|null instance
	 */
	public function getFile()
	{
		return $this->itsConvertedPdfFile;
	}

	/**
	 * Send converted file to stdout
	 * @param string|null $file Final filename to use at client side
	 */
	public function outFile($file = '')
	{
	    if (null === $this->itsConvertedPdfFile) {
	        return null;
        }

		return $this->itsConvertedPdfFile->out($file);
	}
}

/**
 *
 * Class for manipulating pdf file
 * @package FormsAndReports
 *
 * More info --> http://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/
 *
 * Examples:
 * <code>
 * // Initialise the class tool
 * $pdftk = new tldPDFToolKit();
 *
 * // In order to merge multiple PDF file
 * $pdftk->addFile('filepath/file.pdf');
 * $pdftk->addFile('filepath/file1.pdf');
 * $pdftk->addFile('filepath/file2.pdf');
 * $pdftk->merge();
 * $pdftk->out("result.pdf");
 *
 * // In order to stamp a PDF file
 * $pdftk->stamp(
 *      'filepath/fileToStamp.pdf',
 *      'filepath/stampFile.pdf'
 * );
 * $pdftk->out("result.pdf");
 *
 * </code>
 */
class tldPDFToolKit
{

	const WORKING_PATH = '/tmp';
	public $itsFiles;
	public $itsOutputFile;

	function __construct()
	{

	}


	function addFile($file)
	{
		$e = $this->checkFile($file);
		if (is_string($e)) {
			return $e;
		}
		$this->itsFiles[] = $file;
		return;
	}

	function checkFile($filepath)
	{
		$file = new basicFile($filepath);
		// Check if file exists
		if (!$file->isFile()) {
			return "File $filepath not found";
		}
		// Check extension
		$ext = strtoupper($file->getFileExtension());
		if ($ext !== 'PDF') {
			return "File extension '$ext' not valid";
		}
		// Check MIME
		if ($file->getMime() !== 'application/pdf') {
			return 'File is not a pdf from mime information';
		}
		return true;
	}

	function merge($opt = '')
	{
		// Count files
		if (count($this->itsFiles) < 2) {
			return 'Not enough pdf file to merge';
		}
		// Look for options
		$options = null;
		// Prepare command
		$inFiles = escapeshellcmd(implode(' ', $this->itsFiles));
		$outfile = escapeshellcmd(tempnam(self::WORKING_PATH, 'pdftk')) . '.pdf';
		// Do the merge
		$exec_cmd = "pdftk $inFiles cat output $outfile";
		exec($exec_cmd, $exec_output, $exec_status);
		if ($exec_status <> 0) {
			return 'system exec() command error: ' . var_dump($exec_output);
		}
		// if ok, instance the output file with basicFile
		$this->itsOutputFile = new basicFile($outfile);
		return;
	}

	function stamp($fileToStamp, $fileStamp, $opt = [])
	{
		// Check files
		$e = $this->checkFile($fileToStamp);
		if (is_string($e)) {
			return $e;
		}
		$e = $this->checkFile($fileStamp);
		if (is_string($e)) {
			return $e;
		}
		// Escape command
		$outfile = escapeshellcmd(tempnam(self::WORKING_PATH, 'pdftk')) . '.pdf';
		$fileToStamp = escapeshellcmd($fileToStamp);
		$fileStamp = escapeshellcmd($fileStamp);
		// Look for options
		$mode = 'multistamp';
		$allowed_mode = ['stamp', 'multistamp', 'background', 'multibackground'];
		if (!empty($opt['mode']) && in_array($opt['mode'], $allowed_mode)) {
			$mode = escapeshellcmd($opt['mode']);
		}
		// Do the stamp
		$exec_cmd = "pdftk $fileToStamp $mode $fileStamp output $outfile";
		exec($exec_cmd, $exec_output, $exec_status);
		if ($exec_status <> 0) {
			return 'system exec() command error: ' . var_dump($exec_output);
		}
		// if ok, instance the output file with basicFile
		$this->itsOutputFile = new basicFile($outfile);
		return;
	}

	function stampText($fileToStamp, $text, $opt = [])
	{
		// Create stamp file with the text to use
		$html = <<<EOF
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"></head>
<body><p style="width:100%;margin:0;padding:0;text-align:right;font-size:10px;">$text</p></body>
</html>
EOF;
		$pdf = new tldHTML2PDF($html, ['encoding' => 'utf-8', 'margin' => '5mm', 'background' => false]);
		// Stamp
		return $this->stamp(
			$fileToStamp,
			$pdf->itsConvertedPdfFile->getFilePath(),
			$opt
		);
	}

	function out($newFileName = '')
	{
		$this->itsOutputFile->out($newFileName);
	}

}


class tldBarcode
{

	public $itsString;
	public $itsType;
	public $itsOutputFormat;
	public $itsOptions;
	public $itsImage;

	function __construct($string, $type, $options = '')
	{
		$this->itsString = $string;
		$this->itsType = $type;
		$this->itsOptions = $options;
		$this->itsImage = $this->generate();
	}

	function getSupportedTypes()
	{
		return ['Code39', 'Code128', 'Ean13', 'Int25', 'Postnet', 'Upca', 'Upce'];
	}

	function getSupportedOutputFormats()
	{
		return ['jpg', 'png', 'gif'];
	}

	function generate()
	{
		// Do checks
		if (!in_array($type, self::getSupportedTypes())) {
			$this->itsType = 'Code39';
		}
		if (!in_array($this->itsOptions['output'], self::getSupportedOutputFormats())) {
			$this->itsOptions['output'] = 'png';
		}
		// Look for options
		if (empty($this->itsOptions['height']) || !is_int($this->itsOptions['height'])) {
			$this->itsOptions['height'] = 50;
		}
		if (empty($this->itsOptions['width']) || !is_int($this->itsOptions['width'])) {
			$this->itsOptions['width'] = 100;
		}
		// Return the resource
		return Image_Barcode2::draw(
			$this->itsString,
			$this->itsType,
			$this->itsOptions['output'],
			false, // do not send to browser
			$this->itsOptions['height'],
			$this->itsOptions['width'],
			$this->itsOptions['showText'],
			$this->itsOptions['rotation']
		);
	}

	function getImageBase64()
	{
		ob_start();
		switch ($this->itsType) {
			case 'gif':
				imagegif($this->itsImage);
				break;
			case 'jpg':
				imagejpeg($this->itsImage);
				break;
			case 'png':
			default:
				imagepng($this->itsImage);
				break;
		}
		$imgBase64 = base64_encode(ob_get_contents());
		ob_end_clean();
		imagedestroy($this->itsImage);
		return $imgBase64;
	}

	function out()
	{

	}

	function save()
	{

	}

	function toHtml()
	{
		return <<<EOF
<img src="data:image/{$this->itsOptions['output']};base64,{$this->getImageBase64()}">
EOF;
	}

}


class tldModuleReport extends basicFormsAndReports
{

	public $itsModule;
	public $itsReportName;
	public $itsData;
	public $itsOptions;

	function __construct($module, $reportName, $data, $options = '')
	{
		$this->itsModule = $module;
		$this->itsReportName = $reportName;
		$this->itsData = $data;
		$this->itsOptions = $options;
	}

	function fetch()
	{
		// Gets the template
		$templateFilePath = "$this->itsTPLPath/tldModuleReport/$this->itsModule/$this->itsReportName.tpl";
		// Check if exists
		if (!file_exists(dirname(__FILE__) . '/' . $templateFilePath)) {
			return 'Template to display the report not found';
		}
		// Do as usual
		$smarty = $this->getSmarty();
		$smarty->assign('data', $this->itsData);
		$smarty->assign('options', $this->itsOptions);
		// Send results
		return $smarty->fetch($templateFilePath);
	}

}

/**
 * Class to create graph
 * Using HIGHCHART JS
 *
 * <code>
 * try
 * {
 *     $graph = new tldGraph();
 *     $graph->setTitle('Test chart');
 *     $graph->setYAxisTitle('Temperature');
 *     $graph->setXAxisTitle('Month');
 *     $graph->setXAxisCategories(array('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'));
 *     $graph->addBar(
 *         array(7.0, 6.9, 9.5, 14.5, 18.4, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6),
 *         array('name'=>'Tokyo')
 *     );
 *     $graph->addBar(
 *         array(3.9, 4.2, 5.7, 8.5, 11.9, 15.2, 17.0, 16.6, 14.2, 10.3, 6.6, -4.8),
 *         array('name'=>'London')
 *     );
 *     $graph->addGroupTarget(16);
 *     $body.= $graph->fetch();
 * }
 * catch (Exception $e)
 * {
 *     $DEFAULT_ERROR[] = "ERROR: An issue occurred during graph creation. Details: ".$e->getMessage();
 * }
 * </code>
 */
class tldGraph
{

	protected $parameters;

	public function setTitle($title)
	{
		$this->parameters['title']['text'] = $title;
	}

	public function setYAxisTitle($title)
	{
		$this->parameters['yAxis']['title']['text'] = $title;
	}

	public function setYAxisMaxValue($val)
	{
		$this->parameters['yAxis']['max'] = $val;
	}

	public function setYAxisFloorValue($val)
	{
		$this->parameters['yAxis']['floor'] = $val;
	}

	public function setMultipleYAxisTitle($title, $options = [])
	{
		$this->parameters['yAxis'][] = array_replace(
			[
				'title' => ['text' => $title],
			],
			$options
		);
	}

	public function setXAxisTitle($title)
	{
		$this->parameters['xAxis']['title']['text'] = $title;
	}

	public function addXAxisOptions($options)
	{
		$this->parameters['xAxis'] = array_replace(
			$this->parameters['xAxis'] ?: [],
			$options
		);
	}

	public function addYAxisOptions($options)
	{
		$this->parameters['yAxis'] = array_replace(
			$this->parameters['yAxis'] ?: [],
			$options
		);
	}

	public function setTooltip($values, $options = [])
	{
		$this->parameters['tooltip'] = array_replace(
			[
				'enabled' => $values,
			],
			$options);
	}

	public function addChartOptions($options)
	{
		$this->parameters['chart'] = array_replace(
			$this->parameters['chart'] ?: [],
			$options
		);
	}

	public function setXAxisCategories($categories)
	{
		$this->parameters['xAxis']['categories'] = $categories;
	}

	public function getXAxisCategories()
	{
		return $this->parameters['xAxis']['categories'];
	}

	public function addSeries($values, $options = [])
	{
		$this->parameters['series'][] = array_replace(
			[
				'data' => $values,
			],
			$options
		);
	}

	public function addNamedSerie($name, $values, $options = [])
	{
		$this->parameters['series'][] = array_replace(
			[
				'name' => $name,
				'data' => $values,
			],
			$options
		);
	}

	public function addBar($values, $options = [])
	{
		$this->parameters['series'][] = array_replace(
			[
				'type' => 'column',
				'data' => $values,
				'dataLabels' => [
					'enabled' => true,
					'allowOverlap' => true,
				],
				'enableMouseTracking' => false,
			],
			$options
		);
	}

	public function addLine($values, $options = [])
	{
		$this->parameters['series'][] = array_replace(
			[
				'type' => 'line',
				'data' => $values,
				'dataLabels' => [
					'enabled' => true,
					'allowOverlap' => true,
				],
				'enableMouseTracking' => false,
			],
			$options
		);
	}

	public function addScatter($values, $options = [])
	{
		$this->parameters['series'][] = array_replace(
			[
				'type' => 'scatter',
				'data' => $values,
				'marker' => ['radius' => 8],
				'dataLabels' => [
					'enabled' => true,
					'allowOverlap' => true,
				],
				'enableMouseTracking' => false,
			],
			$options
		);
	}

	public function addGroupTarget($val)
	{
		// Generate values from X categories
		$values = [];
		$xAxisCat = $this->getXAxisCategories();
		if (isset($xAxisCat) && !empty($xAxisCat)) {
			foreach ($xAxisCat as $v) {
				$values[] = $val;
			}
		} else {
			throw new Exception('Can not create Group Target, XAxis categories must be set');
		}
		// Prepare options
		$options = [
			'name' => "Group Target ($val)",
			'color' => 'red',
			'dataLabels' => ['enabled' => false],
			'marker' => ['enabled' => false],
			'enableMouseTracking' => false,
		];
		// Add group target line
		$this->addLine($values, $options);
	}

	protected function checkDataSerie($data)
	{
		$countDataEl = count($data ?? []);
		$countCategoriesEl = count($this->getXAxisCategories());
		// check if data elements match Xaxis elements
		if ($countDataEl != $countCategoriesEl) {
			throw new Exception("Data elements provided ($countDataEl) do not match number of X axis categories elements ($countCategoriesEl)");
		}
	}

	protected function encodeParameters()
	{
		return htmlentities(json_encode($this->parameters, JSON_PARTIAL_OUTPUT_ON_ERROR));
	}

	public function fetch($id = null)
	{
		if ($id !== null) {
			return <<<EOF
<div id="$id" class="tldGraph" data-tldgraph="{$this->encodeParameters()}"></div>
EOF;
		}
		return <<<EOF
<div class="tldGraph" data-tldgraph="{$this->encodeParameters()}"></div>
EOF;
	}

}


class tldGraphGeneric
{

	public $itsGraph;
	public $itsOptions;
	public $itsPlotArea;
	public $itsLegend;

	function __construct($options)
	{
		include_once 'Image/Graph.php';
		$this->initOptions($options);
		$this->initGraph();
	}

	private function initOptions($options)
	{
		// Assign options
		$this->itsOptions = $options;
		// Check missing options & default values
		// -- Title text & size
		if (empty($this->itsOptions['title'])) {
			$this->itsOptions['title'] = 'Graph title';
		}
		if (empty($this->itsOptions['titleSize'])) {
			$this->itsOptions['titleSize'] = 14;
		}
		// -- graph size
		if (empty($this->itsOptions['width'])) {
			$this->itsOptions['width'] = 980;
		}
		if (empty($this->itsOptions['height'])) {
			$this->itsOptions['height'] = 500;
		}
		// -- Font text
		if (empty($this->itsOptions['font'])) {
			$this->itsOptions['font'] = 'DejaVuLGCSans-Bold';
		}
		if (empty($this->itsOptions['fontSize'])) {
			$this->itsOptions['fontSize'] = 10;
		}
		if (empty($this->itsOptions['fontColor'])) {
			$this->itsOptions['fontColor'] = 'black';
		}
	}

	private function initGraph()
	{
		// Create main container
		$this->itsGraph = &Image_Graph::factory('graph', [
			$this->itsOptions['width'],
			$this->itsOptions['height'],
		]);
		// Padding
		$this->itsGraph->setPadding(20);
		// Set font
		$Font =& $this->itsGraph->addNew('ttf_font', $this->itsOptions['font'] . '.ttf');
		$Font->setSize($this->itsOptions['fontSize']);
		$Font->setColor($this->itsOptions['fontColor']);
		$this->itsGraph->setFont($Font);
        $plotArea = Image_Graph::factory('plotarea');
        $legend = Image_Graph::factory('legend');

		// Create graph structure and contents
		$this->itsGraph->add(
		// Vertical structure
			Image_Graph::vertical(
			// Title
				Image_Graph::factory('title', [
					$this->itsOptions['title'],
					$this->itsOptions['titleSize'],
				]),
				// Plotarea + Legend
				Image_Graph::vertical(
                    $plotArea,
					$legend,
					90 // take 90 % for plotarea
				),
				10 // take 5 % for title
			)
		);

		// Display legend of plotarea
		$legend->setPlotarea($this->itsPlotArea);

		// Create horizontal scale lines
		$plotArea->addNew('line_grid', IMAGE_GRAPH_AXIS_X);

		// Make sure background and border not visible (white)
		$plotArea->setBackgroundColor('white');
		$plotArea->setBorderColor('white');

		// Axis config --->

		$XAxis = $plotArea->getAxis(IMAGE_GRAPH_AXIS_X);
		$YAxis = $plotArea->getAxis(IMAGE_GRAPH_AXIS_Y);

		// max & min param
		if (!empty($this->itsOptions['xMax'])) {
			$YAxis->forceMaximum($this->itsOptions['xMax']);
		}
		if (!empty($this->itsOptions['xMin'])) {
			$YAxis->forceMinimum($this->itsOptions['xMin']);
		}
		// display or not X & Y scale unit
		if (!empty($this->itsOptions['xScaleUnit'])) {
			$XAxis->setTitle($this->itsOptions['xScaleUnit']);
		}
		if (!empty($this->itsOptions['yScaleUnit'])) {
			$YAxis->setTitle($this->itsOptions['yScaleUnit']);
		}
	}

	function fetch()
	{
		$this->itsGraph->done();
	}

}


/**
 * tldGraphLine class to construct line graph
 * @package FormsAndReports
 *
 * <code>
 * $graph = new tldGraphLine(array(
 *     'title'=>'Note per Month KPI',
 *     'yScaleUnit'=>'Note',
 *     'xScaleUnit'=>'Month',
 * ));
 * $graph->addLine(
 *     array(
 *         'Jan'=>2,
 *         'Feb'=>3,
 *         'Mar'=>5,
 *         'Apr'=>10,
 *         'May'=>4,
 *         'Jun'=>0
 *     ),
 *     array(
 *         'name'=>'Note for Quality',
 *         'color'=>'blue',
 *     )
 * );
 * $graph->addLine(
 *     array(
 *         'Jan'=>5,
 *         'Feb'=>4,
 *         'Mar'=>2,
 *         'Apr'=>18,
 *         'May'=>5,
 *         'Jun'=>9
 *     ),
 *     array(
 *         'name'=>'Note for Reliability',
 *         'color'=>'green',
 *      'groupTarget'=>5,
 *     )
 * );
 * $graph->fetch();
 *
 * </code>
 *
 * See complete API documentation
 * http://pear.php.net/reference/Image_Graph-latest/li_Image_Graph.html
 */
class tldGraphLine extends tldGraphGeneric
{

	function addLine($data, $options)
	{
		// Check options
		// -- case of group target
		if (!empty($options['groupTarget'])) {
			$groupTargetDataset =& Image_Graph::factory('dataset');
			$groupTargetDataset->setName('Group Target');
		}
		// Create dataset
		$Dataset =& Image_Graph::factory('dataset');
		$Dataset->setName($options['name']);
		// Assign values
		foreach ($data as $k => $v) {
			$Dataset->addPoint($k, $v);
			// case there is group target
			if (!$groupTargetDataset) {
				continue;
			}
			$groupTargetDataset->addPoint($k, $options['groupTarget']);
		}
		// Display line
        $plotArea = Image_Graph::factory('plotarea');
		$Plot =& $plotArea->addNew('Image_Graph_Plot_Line', $Dataset);
        $Plot->setLineColor($options['color']);
		$Marker = Image_Graph::factory('Image_Graph_Marker_Circle');
		$Marker->setSize(3);
		$Marker->setFillColor($options['color']);
        $Plot->setMarker($Marker);

		// Display Group target if applicable
		if ($groupTargetDataset) {
            $Plot =& $this->itsPlotArea->addNew('line', [$groupTargetDataset, 'stacked']);
            $Plot->setLineColor('red');
		}
	}

}


class tldGraphBar extends tldGraphGeneric
{

	function addBar($data, $options)
	{
		// Check options
		// -- case of group target
		if (!empty($options['groupTarget'])) {
			$groupTargetDataset =& Image_Graph::factory('dataset');
			$groupTargetDataset->setName('Group Target');
		}
		// Create dataset
		$Dataset =& Image_Graph::factory('dataset');
		$Dataset->setName($options['name']);
		// Assign values
		foreach ($data as $k => $v) {
			$Dataset->addPoint($k, $v);
			// case there is group target
			if (!$groupTargetDataset) {
				continue;
			}
			$groupTargetDataset->addPoint($k, $options['groupTarget']);
		}
		// Display bar
		$Plot =& $this->itsPlotArea->addNew('Image_Graph_Plot_Bar', $Dataset);
		$Plot->setLineColor('black');
		$Plot->setFillColor($options['color']);
		$Marker = Image_Graph::factory('Image_Graph_Marker_Value');
		$Marker->setSize(3);
		$Marker->setFillColor($options['color']);
		$Plot->setMarker($Marker);

		// Display Group target if applicable
		if ($groupTargetDataset) {
			$Plot =& $this->itsPlotArea->addNew('line', [$groupTargetDataset, 'stacked']);
			$Plot->setLineColor('red');
		}
	}

}
