knp_snappy:
    temporary_folder: '%kernel.cache_dir%/snappy'
    pdf:
        enabled:    true
        binary:     '%env(WKHTMLTOPDF_PATH)%'
        options:
            lowquality: false
            enable-local-file-access: true
            quiet: true
    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
    process_timeout: 120
