symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 3600 # 1h lifetime of the link send in the mail
    throttle_limit: 10 # anti-spam : 1 request max by ten seconds by user
    enable_garbage_collection: true # expired token auto clean
