legacy:
    module_mapping:
        acronym: AGR
        people: USER
        position: USER
        department: USER
        acl: USER
        group: USER
        module: MOD
        businessunit: DIR
        location: DIR
        juridicallocation: DIR
        region: DIR
        salesforecast: SFR
        mastersalesforecast: SFR
        forecastclosure: FCR
        competitorpricing: CPR
        customer: ECUST
        customerrelationshipteam: CRT
        competitor: COR
        extranetuser: XU
        extranetuseracl: XU
        extranetuserprofile: XU
        extranetuserfavorite: XU
        heliport: APC
        metropolitanarea: APC
        offlinepoint: APC
        railwaystation: APC
        ferryport: APC
        airport: APC
        busstation: APC
        product: CAT
        producttype: CAT
        productfamily: CAT
        productfamilydms: CAT
        order: SOR
        marketintelligence: MIM
        manufacturingmargin: FINR
        job: JOB
        equipmentrecord: ER
        equipmentserial: ER
        firstarticlequalification: FAQ
        subdivision: DIR
        division: DIR
        tocsparepartsrequest: SPR
        sbsparepartsrequest: SPR
        purchaseorder: PO
        vendoruser: VU
        manual: PUBS
        crab: CRAB
        customer_service_record: CSR
        customerservicerecord: CSR
        technicianoncallcustomerservicerecord: CSR
        commissioningcustomerservicerecord: CSR
        servicebulletincustomerservicerecord: CSR
        technicianoncall: TOC
        equipmentshippingrecord: ESR
        equipmentshippingrecordline: ESR
        supplierranking: SRM
        task: TASK