services:
    _defaults:
        autowire: true

    app.mailer.pool.abstract:
        class: App\Mailer\AbstractPoolMailer

    App\Mailer\Sales\OrdersPoolMailer:
        parent: app.mailer.pool.abstract
        autowire: true

    App\Mailer\ErrorsPoolMailer:
        parent: app.mailer.pool.abstract
        autowire: true

    App\Mailer\Module\ChangelogPoolMailer:
        parent: app.mailer.pool.abstract
        autowire: true
