@startuml
PLANNED: WS has planned the delivery
REQUESTED: from PIO

'Final idea with picking group
[*] --> CREATED_FROM_BAAN
CREATED_FROM_BAAN --> PLANNED
CREATED_FROM_BAAN --> REQUESTED
REQUESTED --> PLANNED
PLANNED --> START_DELIVERY
START_DELIVERY --> DELIVERED_PARTIALLY
DELIVERED_PARTIALLY --> CLOSED

'Implemented
[*] --> CREATED_FROM_BAAN
CREATED_FROM_BAAN --> DELIVERED_PARTIALLY
DELIVERED_PARTIALLY --> CLOSED
@enduml
