<?php

declare(strict_types=1);

namespace Application\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251210090225 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Update schema after upgrade';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE acl CHANGE legacy_id legacy_id INT NOT NULL');
        $this->addSql('ALTER TABLE acronym CHANGE url url VARCHAR(120) DEFAULT NULL');
        $this->addSql('ALTER TABLE activity CHANGE change_set change_set JSON DEFAULT NULL, CHANGE metadata metadata JSON DEFAULT \'[]\' NOT NULL');
        $this->addSql('ALTER TABLE change_logs CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE author_id author_id INT NOT NULL, CHANGE hash hash VARCHAR(255) NOT NULL, CHANGE date date DATETIME NOT NULL, CHANGE message message VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE competitor_pricings CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE forecast_closure_id forecast_closure_id INT DEFAULT NULL, CHANGE poster_id poster_id INT NOT NULL, CHANGE competitor_id competitor_id INT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE competitor_model competitor_model VARCHAR(255) DEFAULT NULL, CHANGE quantity quantity INT DEFAULT NULL, CHANGE currency currency VARCHAR(10) DEFAULT NULL, CHANGE incoterms incoterms VARCHAR(3) DEFAULT NULL, CHANGE incoterms_location incoterms_location VARCHAR(255) DEFAULT NULL, CHANGE legacy_id legacy_id INT NOT NULL');
        $this->addSql('ALTER TABLE competitor_pricings_files CHANGE id id INT NOT NULL, CHANGE competitor_pricing_id competitor_pricing_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE competitors CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(50) NOT NULL, CHANGE short_description short_description VARCHAR(100) DEFAULT NULL, CHANGE url url VARCHAR(100) DEFAULT NULL, CHANGE legacy_id legacy_id INT NOT NULL');
        $this->addSql('ALTER TABLE competitor_product_type CHANGE competitor_id competitor_id INT NOT NULL, CHANGE product_type_id product_type_id INT NOT NULL');
        $this->addSql('ALTER TABLE competitors_files CHANGE id id INT NOT NULL, CHANGE competitor_id competitor_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE continents CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE iso_code_2 iso_code_2 VARCHAR(2) NOT NULL, CHANGE name name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE contract CHANGE internal_party internal_party JSON DEFAULT \'[]\' NOT NULL, CHANGE other_party_signatories other_party_signatories JSON DEFAULT \'[]\' NOT NULL');
        $this->addSql('ALTER TABLE countries CHANGE fips_code fips_code VARCHAR(10) DEFAULT NULL, CHANGE fips_name fips_name VARCHAR(100) DEFAULT NULL, CHANGE latitude latitude VARCHAR(20) DEFAULT NULL, CHANGE longitude longitude VARCHAR(20) DEFAULT NULL, CHANGE continent_id continent_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE currencies CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(3) NOT NULL, CHANGE legacy_id legacy_id INT NOT NULL');
        $this->addSql('ALTER TABLE customer_relationship_teams CHANGE customer_id customer_id INT DEFAULT NULL, CHANGE sales_representative_id sales_representative_id INT DEFAULT NULL, CHANGE parts_representative_id parts_representative_id INT DEFAULT NULL, CHANGE service_representative_id service_representative_id INT DEFAULT NULL, CHANGE parts_location_id parts_location_id INT DEFAULT NULL, CHANGE service_location_id service_location_id INT DEFAULT NULL, CHANGE erp_location_id erp_location_id INT DEFAULT NULL, CHANGE customer_number customer_number VARCHAR(6) DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE task_id task_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE customers CHANGE parent_customer_id parent_customer_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE phone phone VARCHAR(60) DEFAULT NULL, CHANGE fax fax VARCHAR(60) DEFAULT NULL, CHANGE url url VARCHAR(255) DEFAULT NULL, CHANGE address_street1 address_street1 VARCHAR(255) DEFAULT NULL, CHANGE address_street2 address_street2 VARCHAR(255) DEFAULT NULL, CHANGE address_postal_code address_postal_code VARCHAR(20) DEFAULT NULL, CHANGE address_city address_city VARCHAR(50) DEFAULT NULL, CHANGE address_town address_town VARCHAR(50) DEFAULT NULL, CHANGE address_state address_state VARCHAR(50) DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE country_id country_id INT DEFAULT NULL, CHANGE status status VARCHAR(20) DEFAULT NULL, CHANGE validated_at validated_at DATETIME DEFAULT NULL, CHANGE infor_ln_business_partner_codes infor_ln_business_partner_codes TINYTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE customers_files CHANGE id id INT NOT NULL, CHANGE customer_id customer_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE demos CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE sso_id sso_id INT NOT NULL, CHANGE factory_id factory_id INT NOT NULL, CHANGE asm_id asm_id INT NOT NULL, CHANGE psm_id psm_id INT NOT NULL, CHANGE product_id product_id INT NOT NULL, CHANGE customer_id customer_id INT NOT NULL, CHANGE country_id country_id INT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE demo_people CHANGE demo_id demo_id INT NOT NULL, CHANGE people_id people_id INT NOT NULL');
        $this->addSql('ALTER TABLE demos_files CHANGE id id INT NOT NULL, CHANGE demo_id demo_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE directory_juridical_location CHANGE address_postal_code address_postal_code VARCHAR(20) DEFAULT NULL, CHANGE address_city address_city VARCHAR(50) DEFAULT NULL, CHANGE address_state address_state VARCHAR(50) DEFAULT NULL, CHANGE address_country address_country VARCHAR(2) DEFAULT NULL, CHANGE address_street1 address_street1 VARCHAR(255) DEFAULT NULL, CHANGE address_street2 address_street2 VARCHAR(255) DEFAULT NULL, CHANGE address_town address_town VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE directory_networks CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE dms CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE owner_id owner_id INT DEFAULT NULL, CHANGE title title VARCHAR(255) NOT NULL, CHANGE subject subject VARCHAR(255) NOT NULL, CHANGE language language VARCHAR(32) NOT NULL, CHANGE legacy_id legacy_id INT NOT NULL');
        $this->addSql('ALTER TABLE emission_ratings CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE legacy_id legacy_id INT NOT NULL');
        $this->addSql('ALTER TABLE equipment_accidents CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE equipment_accidents_files CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE equipment_follow_up_reports CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE created_by created_by INT NOT NULL, CHANGE updated_by updated_by INT DEFAULT NULL, CHANGE equipment_record_id equipment_record_id INT NOT NULL, CHANGE operational_status_id operational_status_id INT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL, CHANGE hourmeter hourmeter INT NOT NULL, CHANGE odometer odometer INT DEFAULT NULL, CHANGE equipment_accident_id equipment_accident_id INT DEFAULT NULL, CHANGE equipment_maintenance_id equipment_maintenance_id INT DEFAULT NULL, CHANGE hourmeter_totalizer hourmeter_totalizer INT NOT NULL');
        $this->addSql('ALTER TABLE equipment_hourmeter_resets CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE created_by created_by INT NOT NULL, CHANGE equipment_record_id equipment_record_id INT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE hourmeter hourmeter INT NOT NULL');
        $this->addSql('ALTER TABLE equipment_maintenance_files CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE equipment_maintenances CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE type type INT NOT NULL');
        $this->addSql('ALTER TABLE equipment_records CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE parent_equipment_id parent_equipment_id INT DEFAULT NULL, CHANGE serial_number serial_number VARCHAR(20) NOT NULL, CHANGE customer_serial_number customer_serial_number VARCHAR(30) DEFAULT NULL, CHANGE location location VARCHAR(20) DEFAULT NULL, CHANGE legacy_id legacy_id INT NOT NULL, CHANGE airport_id airport_id INT DEFAULT NULL, CHANGE product_id product_id INT DEFAULT NULL, CHANGE model model VARCHAR(30) DEFAULT NULL, CHANGE type type VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE exchange_rates CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE currency_id currency_id INT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE type type VARCHAR(3) NOT NULL, CHANGE legacy_id legacy_id INT NOT NULL');
        $this->addSql('ALTER TABLE ext_translations CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE locale locale VARCHAR(8) NOT NULL, CHANGE field field VARCHAR(32) NOT NULL, CHANGE foreign_key foreign_key VARCHAR(64) NOT NULL');
        $this->addSql('ALTER TABLE extranet_user_acl CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE extranet_user_id extranet_user_id INT NOT NULL, CHANGE crt_id crt_id INT NOT NULL, CHANGE extranet_user_group_id extranet_user_group_id INT NOT NULL, CHANGE c_del c_del VARCHAR(3) DEFAULT NULL, CHANGE legacy_id legacy_id INT NOT NULL');
        $this->addSql('ALTER TABLE extranet_user_favorite CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE extranet_user_id extranet_user_id INT NOT NULL, CHANGE aero_username aero_username VARCHAR(255) DEFAULT NULL, CHANGE part_number part_number VARCHAR(255) DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE legacy_id legacy_id INT NOT NULL');
        $this->addSql('ALTER TABLE extranet_user_group CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(50) NOT NULL, CHANGE description description VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE extranet_user_profile CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE country_id country_id INT DEFAULT NULL, CHANGE customer customer INT DEFAULT NULL, CHANGE erp_location erp_location INT DEFAULT NULL, CHANGE type type VARCHAR(255) DEFAULT NULL, CHANGE division division VARCHAR(255) DEFAULT NULL, CHANGE department department VARCHAR(255) DEFAULT NULL, CHANGE job_title job_title VARCHAR(255) DEFAULT NULL, CHANGE language language VARCHAR(2) DEFAULT NULL, CHANGE counter counter INT NOT NULL, CHANGE customer_carrier_name customer_carrier_name VARCHAR(255) DEFAULT NULL, CHANGE company_name company_name VARCHAR(255) DEFAULT NULL, CHANGE note note VARCHAR(255) DEFAULT NULL, CHANGE shipping_account_number shipping_account_number VARCHAR(255) DEFAULT NULL, CHANGE requestor_number requestor_number VARCHAR(255) DEFAULT NULL, CHANGE employee_number employee_number VARCHAR(255) DEFAULT NULL, CHANGE legacy_id legacy_id INT NOT NULL, CHANGE address_street1 address_street1 VARCHAR(255) DEFAULT NULL, CHANGE address_street2 address_street2 VARCHAR(255) DEFAULT NULL, CHANGE address_postal_code address_postal_code VARCHAR(20) DEFAULT NULL, CHANGE address_city address_city VARCHAR(50) DEFAULT NULL, CHANGE address_town address_town VARCHAR(50) DEFAULT NULL, CHANGE address_state address_state VARCHAR(50) DEFAULT NULL, CHANGE shipping_address_country shipping_address_country VARCHAR(2) DEFAULT NULL, CHANGE shipping_address_street1 shipping_address_street1 VARCHAR(255) DEFAULT NULL, CHANGE shipping_address_street2 shipping_address_street2 VARCHAR(255) DEFAULT NULL, CHANGE shipping_address_postal_code shipping_address_postal_code VARCHAR(20) DEFAULT NULL, CHANGE shipping_address_city shipping_address_city VARCHAR(50) DEFAULT NULL, CHANGE shipping_address_town shipping_address_town VARCHAR(50) DEFAULT NULL, CHANGE shipping_address_state shipping_address_state VARCHAR(50) DEFAULT NULL, CHANGE sequence_ids sequence_ids TINYTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE families CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE discr discr VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE finance_families CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE finance_family_location CHANGE finance_family_id finance_family_id INT NOT NULL, CHANGE location_id location_id INT NOT NULL');
        $this->addSql('ALTER TABLE finance_family_pricing CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE finance_family_id finance_family_id INT NOT NULL, CHANGE sso_id sso_id INT NOT NULL, CHANGE factory_id factory_id INT NOT NULL, CHANGE average_price average_price INT NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE first_article_qualifications CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE location_id location_id INT NOT NULL, CHANGE buyer_id buyer_id INT DEFAULT NULL, CHANGE poster_id poster_id INT NOT NULL, CHANGE owner_id owner_id INT NOT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE supplier_name supplier_name VARCHAR(255) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE completed_at completed_at DATETIME DEFAULT NULL, CHANGE plan_definition_completed_at plan_definition_completed_at DATETIME DEFAULT NULL, CHANGE eap eap INT DEFAULT NULL, CHANGE status status VARCHAR(255) NOT NULL, CHANGE meap meap INT DEFAULT NULL');
        $this->addSql('ALTER TABLE first_article_qualifications_members CHANGE first_article_qualification_id first_article_qualification_id INT NOT NULL, CHANGE people_id people_id INT NOT NULL');
        $this->addSql('ALTER TABLE first_article_qualifications_equipment_records CHANGE first_article_qualification_id first_article_qualification_id INT NOT NULL, CHANGE equipment_record_id equipment_record_id INT NOT NULL');
        $this->addSql('ALTER TABLE first_article_qualifications_files CHANGE id id INT NOT NULL, CHANGE first_article_qualification_id first_article_qualification_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE first_article_qualifications_part_numbers CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE first_article_qualification_id first_article_qualification_id INT NOT NULL, CHANGE revision revision VARCHAR(6) NOT NULL, CHANGE description description VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE first_article_qualifications_plan_item_types CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE description description VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE first_article_qualifications_plan_items CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE type_id type_id INT NOT NULL, CHANGE first_article_qualification_id first_article_qualification_id INT NOT NULL, CHANGE validated_by_id validated_by_id INT DEFAULT NULL, CHANGE validated_at validated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE first_article_qualifications_tags CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE first_article_qualifications_tags_xref CHANGE first_article_qualification_tag_id first_article_qualification_tag_id INT NOT NULL, CHANGE first_article_qualification_id first_article_qualification_id INT NOT NULL');
        $this->addSql('ALTER TABLE forecast_closures CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE sales_forecast_id sales_forecast_id INT NOT NULL, CHANGE poster_id poster_id INT NOT NULL, CHANGE status status VARCHAR(255) NOT NULL, CHANGE ordered_quantity ordered_quantity INT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE currency currency VARCHAR(10) DEFAULT NULL, CHANGE legacy_id legacy_id INT NOT NULL, CHANGE competitor_id competitor_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE forecast_closures_files CHANGE id id INT NOT NULL, CHANGE forecast_closure_id forecast_closure_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE freight_forwarders CHANGE emails emails TEXT NOT NULL');
        $this->addSql('ALTER TABLE iata_codes CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE country_id country_id INT DEFAULT NULL, CHANGE city_code_3 city_code_3 VARCHAR(3) DEFAULT NULL, CHANGE city_name city_name VARCHAR(60) NOT NULL, CHANGE state state VARCHAR(60) DEFAULT NULL, CHANGE code code VARCHAR(10) NOT NULL, CHANGE name name VARCHAR(22) DEFAULT NULL, CHANGE source source VARCHAR(10) NOT NULL, CHANGE type type VARCHAR(60) NOT NULL, CHANGE legacy_id legacy_id INT NOT NULL, CHANGE discr discr VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE location_cleanliness CHANGE location_id location_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE maintenance_contracts CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE end_user_id end_user_id INT NOT NULL, CHANGE buyer_id buyer_id INT NOT NULL, CHANGE representative_id representative_id INT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE description description VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE maintenance_contracts_equipment_records CHANGE maintenance_contract_id maintenance_contract_id INT NOT NULL, CHANGE equipment_record_id equipment_record_id INT NOT NULL');
        $this->addSql('ALTER TABLE maintenance_contracts_user_xus CHANGE maintenance_contract_id maintenance_contract_id INT NOT NULL, CHANGE extranet_user_id extranet_user_id INT NOT NULL');
        $this->addSql('ALTER TABLE maintenance_contracts_buyer_xus CHANGE maintenance_contract_id maintenance_contract_id INT NOT NULL, CHANGE extranet_user_id extranet_user_id INT NOT NULL');
        $this->addSql('ALTER TABLE manual_prints CHANGE id id BINARY(16) NOT NULL');
        $this->addSql('ALTER TABLE market_intelligence CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE legacy_id legacy_id INT DEFAULT NULL, CHANGE poster_id poster_id INT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE short_description short_description VARCHAR(75) NOT NULL, CHANGE suppliers suppliers LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE market_intelligence_customer CHANGE market_intelligence_id market_intelligence_id INT NOT NULL, CHANGE customer_id customer_id INT NOT NULL');
        $this->addSql('ALTER TABLE market_intelligence_competitor CHANGE market_intelligence_id market_intelligence_id INT NOT NULL, CHANGE competitor_id competitor_id INT NOT NULL');
        $this->addSql('ALTER TABLE market_intelligence_product_type CHANGE market_intelligence_id market_intelligence_id INT NOT NULL, CHANGE product_type_id product_type_id INT NOT NULL');
        $this->addSql('ALTER TABLE market_intelligence_dependencies CHANGE market_intelligence_id market_intelligence_id INT NOT NULL, CHANGE market_intelligence_linked_id market_intelligence_linked_id INT NOT NULL');
        $this->addSql('ALTER TABLE market_intelligence_files CHANGE id id INT NOT NULL, CHANGE market_intelligence_id market_intelligence_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE market_intelligence_subscription CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE competitor_id competitor_id INT DEFAULT NULL, CHANGE customer_id customer_id INT DEFAULT NULL, CHANGE product_type_id product_type_id INT DEFAULT NULL, CHANGE subscriber_id subscriber_id INT NOT NULL');
        $this->addSql('ALTER TABLE news CHANGE category_id category_id INT DEFAULT NULL, CHANGE people_id people_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE out_of_tolerance_form CHANGE deletedAt deletedAt DATETIME DEFAULT NULL, CHANGE analysisBy analysisBy INT DEFAULT NULL');
        $this->addSql('ALTER TABLE out_of_tolerance_form_files CHANGE out_of_tolerance_form_id out_of_tolerance_form_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE power_bi_reports CHANGE power_bi_uuid_object power_bi_uuid_object BINARY(16) NOT NULL');
        $this->addSql('ALTER TABLE product_dms CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE product_id product_id INT DEFAULT NULL, CHANGE dms_id dms_id INT NOT NULL, CHANGE dms_type dms_type VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE product_families CHANGE id id INT NOT NULL, CHANGE product_type_id product_type_id INT DEFAULT NULL, CHANGE legacy_id legacy_id INT NOT NULL');
        $this->addSql('ALTER TABLE product_family_dms CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE dms_id dms_id INT NOT NULL, CHANGE dms_type dms_type VARCHAR(255) DEFAULT NULL, CHANGE legacy_id legacy_id INT NOT NULL');
        $this->addSql('ALTER TABLE product_types CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE english_name english_name VARCHAR(255) DEFAULT NULL, CHANGE french_name french_name VARCHAR(255) DEFAULT NULL, CHANGE spanish_name spanish_name VARCHAR(255) DEFAULT NULL, CHANGE portuguese_name portuguese_name VARCHAR(255) DEFAULT NULL, CHANGE chinese_name chinese_name VARCHAR(255) DEFAULT NULL, CHANGE japanese_name japanese_name VARCHAR(255) DEFAULT NULL, CHANGE german_name german_name VARCHAR(255) DEFAULT NULL, CHANGE russian_name russian_name VARCHAR(255) DEFAULT NULL, CHANGE dms_id dms_id INT DEFAULT NULL, CHANGE legacy_id legacy_id INT NOT NULL');
        $this->addSql('ALTER TABLE products CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE family_id family_id INT NOT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE legacy_id legacy_id INT NOT NULL');
        $this->addSql('ALTER TABLE report_snapshot CHANGE options options JSON NOT NULL, CHANGE x_totals x_totals JSON NOT NULL, CHANGE y_totals y_totals JSON NOT NULL, CHANGE `rows` `rows` JSON NOT NULL, CHANGE metadata metadata JSON NOT NULL');
        $this->addSql('ALTER TABLE sales_areas CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE country_id country_id INT NOT NULL, CHANGE asm_id asm_id INT NOT NULL, CHANGE sso_id sso_id INT NOT NULL');
        $this->addSql('ALTER TABLE sales_forecasts CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE sso_id sso_id INT NOT NULL, CHANGE factory_id factory_id INT NOT NULL, CHANGE asm_id asm_id INT NOT NULL, CHANGE poster_id poster_id INT NOT NULL, CHANGE third_party_id third_party_id INT DEFAULT NULL, CHANGE airport_id airport_id INT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE status status VARCHAR(255) NOT NULL, CHANGE equote_id equote_id VARCHAR(255) DEFAULT NULL, CHANGE quantity quantity INT NOT NULL, CHANGE legacy_id legacy_id INT NOT NULL, CHANGE country_id country_id INT DEFAULT NULL, CHANGE last_commented_at last_commented_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE sales_forecasts_files CHANGE id id INT NOT NULL, CHANGE sales_forecast_id sales_forecast_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE sales_forecasts_master CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE legacy_id legacy_id INT NOT NULL');
        $this->addSql('ALTER TABLE sales_orders CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE sso_id sso_id INT NOT NULL, CHANGE juridical_location_id juridical_location_id INT DEFAULT NULL, CHANGE asm_id asm_id INT DEFAULT NULL, CHANGE buyer_id buyer_id INT DEFAULT NULL, CHANGE end_user_id end_user_id INT DEFAULT NULL, CHANGE sales_agent_id sales_agent_id INT DEFAULT NULL, CHANGE entered_at entered_at DATETIME NOT NULL, CHANGE closed_at closed_at DATETIME DEFAULT NULL, CHANGE status status VARCHAR(20) NOT NULL, CHANGE equote_id equote_id VARCHAR(20) DEFAULT NULL, CHANGE baan_order_numbers baan_order_numbers TINYTEXT DEFAULT NULL, CHANGE customer_name customer_name VARCHAR(255) NOT NULL, CHANGE customer_purchase_orders customer_purchase_orders TINYTEXT DEFAULT NULL, CHANGE legacy_id legacy_id INT NOT NULL');
        $this->addSql('ALTER TABLE sales_orders_files CHANGE id id INT NOT NULL, CHANGE order_id order_id INT NOT NULL');
        $this->addSql('ALTER TABLE spq_attached_files CHANGE quotation_id quotation_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE spq_quotation_files CHANGE quotation_id quotation_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE spq_quotation_lines CHANGE quotation_id quotation_id INT NOT NULL, CHANGE sales_unit sales_unit VARCHAR(3) NOT NULL, CHANGE item_type item_type VARCHAR(14) NOT NULL');
        $this->addSql('ALTER TABLE spq_quotations CHANGE incoterms incoterms VARCHAR(3) NOT NULL, CHANGE delivery_address_baan_id delivery_address_baan_id VARCHAR(3) NOT NULL, CHANGE billing_address_baan_id billing_address_baan_id VARCHAR(3) NOT NULL, CHANGE currency currency VARCHAR(3) NOT NULL');
        $this->addSql('ALTER TABLE survey_answers CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE value value INT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE survey_campaigns CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE description description VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE survey_comments CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE survey_groups CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE survey_id survey_id INT DEFAULT NULL, CHANGE created_by created_by INT NOT NULL, CHANGE updated_by updated_by INT DEFAULT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE sorting sorting INT DEFAULT NULL, CHANGE deletedAt deletedAt DATETIME DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE survey_items CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE group_id group_id INT DEFAULT NULL, CHANGE survey_id survey_id INT DEFAULT NULL, CHANGE created_by created_by INT NOT NULL, CHANGE updated_by updated_by INT DEFAULT NULL, CHANGE deletedAt deletedAt DATETIME DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE survey_published_surveys CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE token token VARCHAR(255) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL, CHANGE target_type target_type VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE survey_rating_types CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE survey_id survey_id INT DEFAULT NULL, CHANGE min min INT NOT NULL, CHANGE max max INT NOT NULL, CHANGE min_label min_label VARCHAR(255) NOT NULL, CHANGE max_label max_label VARCHAR(255) NOT NULL, CHANGE deletedAt deletedAt DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE surveys CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE created_by created_by INT NOT NULL, CHANGE updated_by updated_by INT DEFAULT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE expiration_date expiration_date DATETIME DEFAULT NULL, CHANGE deletedAt deletedAt DATETIME DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE tags CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE created_by created_by INT DEFAULT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE discr discr VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE tool CHANGE status status VARCHAR(25) NOT NULL');
        $this->addSql('ALTER TABLE trainings CHANGE starting_at starting_at DATETIME NOT NULL, CHANGE ending_at ending_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE unit_operational_statuses CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(3) NOT NULL, CHANGE description description VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE user CHANGE email email VARCHAR(255) NOT NULL, CHANGE firstname firstname VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE user_setting CHANGE settings settings JSON DEFAULT \'[]\' NOT NULL');
        $this->addSql('ALTER TABLE user_story CHANGE people_properties people_properties LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE user_story_emails CHANGE people_properties people_properties LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE warehouse_tasks_mappings CHANGE inbound_tasks inbound_tasks TINYTEXT NOT NULL, CHANGE outbound_tasks outbound_tasks TINYTEXT NOT NULL, CHANGE administrative_tasks administrative_tasks TINYTEXT NOT NULL, CHANGE excluded_tasks excluded_tasks TINYTEXT NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE competitors_files CHANGE competitor_id competitor_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE id id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE equipment_maintenance_files CHANGE id id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE extranet_user_group CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE name name VARCHAR(50) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE description description VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\'');
        $this->addSql('ALTER TABLE equipment_maintenances CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE type type INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE market_intelligence_product_type CHANGE market_intelligence_id market_intelligence_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE product_type_id product_type_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE countries CHANGE fips_code fips_code VARCHAR(10) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE fips_name fips_name VARCHAR(100) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE latitude latitude VARCHAR(20) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE longitude longitude VARCHAR(20) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE continent_id continent_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE contract CHANGE internal_party internal_party JSON DEFAULT \'[]\' NOT NULL COMMENT \'(DC2Type:json)\', CHANGE other_party_signatories other_party_signatories JSON DEFAULT \'[]\' NOT NULL COMMENT \'(DC2Type:json)\'');
        $this->addSql('ALTER TABLE competitor_pricings CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE competitor_model competitor_model VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE quantity quantity INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE currency currency VARCHAR(10) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE incoterms incoterms VARCHAR(3) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE incoterms_location incoterms_location VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE legacy_id legacy_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE forecast_closure_id forecast_closure_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE poster_id poster_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE competitor_id competitor_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE survey_rating_types CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE min min INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE max max INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE min_label min_label VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE max_label max_label VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE deletedAt deletedAt DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', CHANGE survey_id survey_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE finance_family_pricing CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE average_price average_price INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE updated_at updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE finance_family_id finance_family_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE sso_id sso_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE factory_id factory_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE ext_translations CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE locale locale VARCHAR(8) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE field field VARCHAR(32) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE foreign_key foreign_key VARCHAR(64) NOT NULL COMMENT \'(DC2Type:string)\'');
        $this->addSql('ALTER TABLE spq_quotation_lines CHANGE sales_unit sales_unit VARCHAR(3) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE item_type item_type VARCHAR(14) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE quotation_id quotation_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE market_intelligence_customer CHANGE market_intelligence_id market_intelligence_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE customer_id customer_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE extranet_user_favorite CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE aero_username aero_username VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE part_number part_number VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE description description VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE legacy_id legacy_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE extranet_user_id extranet_user_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE market_intelligence_dependencies CHANGE market_intelligence_id market_intelligence_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE market_intelligence_linked_id market_intelligence_linked_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE finance_family_location CHANGE finance_family_id finance_family_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE location_id location_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE dms CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE title title VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE subject subject VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE language language VARCHAR(32) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE legacy_id legacy_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE owner_id owner_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE emission_ratings CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE name name VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE legacy_id legacy_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE customers CHANGE name name VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE phone phone VARCHAR(60) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE fax fax VARCHAR(60) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE url url VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE deleted_at deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', CHANGE status status VARCHAR(20) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE validated_at validated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', CHANGE infor_ln_business_partner_codes infor_ln_business_partner_codes TINYTEXT DEFAULT NULL COMMENT \'(DC2Type:simple_array)\', CHANGE address_street1 address_street1 VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE address_street2 address_street2 VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE address_postal_code address_postal_code VARCHAR(20) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE address_city address_city VARCHAR(50) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE address_town address_town VARCHAR(50) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE address_state address_state VARCHAR(50) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE parent_customer_id parent_customer_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE country_id country_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE competitors CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE name name VARCHAR(50) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE short_description short_description VARCHAR(100) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE url url VARCHAR(100) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE legacy_id legacy_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE competitor_product_type CHANGE competitor_id competitor_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE product_type_id product_type_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE first_article_qualifications_members CHANGE first_article_qualification_id first_article_qualification_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE people_id people_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE warehouse_tasks_mappings CHANGE inbound_tasks inbound_tasks TINYTEXT NOT NULL COMMENT \'(DC2Type:simple_array)\', CHANGE outbound_tasks outbound_tasks TINYTEXT NOT NULL COMMENT \'(DC2Type:simple_array)\', CHANGE administrative_tasks administrative_tasks TINYTEXT NOT NULL COMMENT \'(DC2Type:simple_array)\', CHANGE excluded_tasks excluded_tasks TINYTEXT NOT NULL COMMENT \'(DC2Type:simple_array)\'');
        $this->addSql('ALTER TABLE maintenance_contracts_user_xus CHANGE maintenance_contract_id maintenance_contract_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE extranet_user_id extranet_user_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE products CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE name name VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE legacy_id legacy_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE family_id family_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE survey_published_surveys CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE token token VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE updated_at updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE target_type target_type VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\'');
        $this->addSql('ALTER TABLE forecast_closures CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE status status VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE ordered_quantity ordered_quantity INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE currency currency VARCHAR(10) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE legacy_id legacy_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE sales_forecast_id sales_forecast_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE poster_id poster_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE competitor_id competitor_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE survey_groups CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE name name VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE sorting sorting INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE deletedAt deletedAt DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE updated_at updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE survey_id survey_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE created_by created_by INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE updated_by updated_by INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE spq_quotation_files CHANGE quotation_id quotation_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE sales_forecasts CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE last_commented_at last_commented_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', CHANGE status status VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE equote_id equote_id VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE quantity quantity INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE legacy_id legacy_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE sso_id sso_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE factory_id factory_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE asm_id asm_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE poster_id poster_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE third_party_id third_party_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE country_id country_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE airport_id airport_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE equipment_records CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE serial_number serial_number VARCHAR(20) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE customer_serial_number customer_serial_number VARCHAR(30) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE model model VARCHAR(30) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE type type VARCHAR(50) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE location location VARCHAR(20) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE legacy_id legacy_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE product_id product_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE airport_id airport_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE parent_equipment_id parent_equipment_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE customers_files CHANGE customer_id customer_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE id id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE continents CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE iso_code_2 iso_code_2 VARCHAR(2) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE name name VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\'');
        $this->addSql('ALTER TABLE survey_comments CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE updated_at updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\'');
        $this->addSql('ALTER TABLE exchange_rates CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE type type VARCHAR(3) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE legacy_id legacy_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE currency_id currency_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE power_bi_reports CHANGE power_bi_uuid_object power_bi_uuid_object BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE sales_orders CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE entered_at entered_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE closed_at closed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', CHANGE status status VARCHAR(20) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE equote_id equote_id VARCHAR(20) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE baan_order_numbers baan_order_numbers TINYTEXT DEFAULT NULL COMMENT \'(DC2Type:simple_array)\', CHANGE customer_name customer_name VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE customer_purchase_orders customer_purchase_orders TINYTEXT DEFAULT NULL COMMENT \'(DC2Type:simple_array)\', CHANGE legacy_id legacy_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE sso_id sso_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE juridical_location_id juridical_location_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE asm_id asm_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE buyer_id buyer_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE end_user_id end_user_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE sales_agent_id sales_agent_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE activity CHANGE metadata metadata JSON DEFAULT \'[]\' NOT NULL COMMENT \'(DC2Type:json)\', CHANGE change_set change_set JSON DEFAULT NULL COMMENT \'(DC2Type:json)\'');
        $this->addSql('ALTER TABLE survey_campaigns CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE description description VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\'');
        $this->addSql('ALTER TABLE tags CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE name name VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE created_by created_by INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE discr discr VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\'');
        $this->addSql('ALTER TABLE demo_people CHANGE demo_id demo_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE people_id people_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE acl CHANGE legacy_id legacy_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE iata_codes CHANGE code code VARCHAR(10) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE type type VARCHAR(60) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE city_code_3 city_code_3 VARCHAR(3) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE city_name city_name VARCHAR(60) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE state state VARCHAR(60) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE name name VARCHAR(22) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE source source VARCHAR(10) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE legacy_id legacy_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE country_id country_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE discr discr VARCHAR(20) NOT NULL COMMENT \'(DC2Type:string)\'');
        $this->addSql('ALTER TABLE surveys CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE name name VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE expiration_date expiration_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', CHANGE deletedAt deletedAt DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE updated_at updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE created_by created_by INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE updated_by updated_by INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE spq_quotations CHANGE delivery_address_baan_id delivery_address_baan_id VARCHAR(3) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE billing_address_baan_id billing_address_baan_id VARCHAR(3) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE incoterms incoterms VARCHAR(3) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE currency currency VARCHAR(3) NOT NULL COMMENT \'(DC2Type:string)\'');
        $this->addSql('ALTER TABLE sales_forecasts_master CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE legacy_id legacy_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE product_families CHANGE legacy_id legacy_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE product_type_id product_type_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE id id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE spq_attached_files CHANGE quotation_id quotation_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE finance_families CHANGE id id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE extranet_user_profile CHANGE type type VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE division division VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE customer_carrier_name customer_carrier_name VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE shipping_account_number shipping_account_number VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE requestor_number requestor_number VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE employee_number employee_number VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE sequence_ids sequence_ids TINYTEXT DEFAULT NULL COMMENT \'(DC2Type:simple_array)\', CHANGE legacy_id legacy_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE job_title job_title VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE department department VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE language language VARCHAR(2) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE note note VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE company_name company_name VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE counter counter INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE shipping_address_country shipping_address_country VARCHAR(2) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE shipping_address_street1 shipping_address_street1 VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE shipping_address_street2 shipping_address_street2 VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE shipping_address_postal_code shipping_address_postal_code VARCHAR(20) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE shipping_address_city shipping_address_city VARCHAR(50) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE shipping_address_town shipping_address_town VARCHAR(50) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE shipping_address_state shipping_address_state VARCHAR(50) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE address_street1 address_street1 VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE address_street2 address_street2 VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE address_postal_code address_postal_code VARCHAR(20) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE address_city address_city VARCHAR(50) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE address_town address_town VARCHAR(50) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE address_state address_state VARCHAR(50) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE customer customer INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE erp_location erp_location INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE country_id country_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE location_cleanliness CHANGE location_id location_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE first_article_qualifications_plan_item_types CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE description description VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\'');
        $this->addSql('ALTER TABLE extranet_user_acl CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE c_del c_del VARCHAR(3) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE legacy_id legacy_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE extranet_user_id extranet_user_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE crt_id crt_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE extranet_user_group_id extranet_user_group_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE survey_items CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE deletedAt deletedAt DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE updated_at updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE group_id group_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE survey_id survey_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE created_by created_by INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE updated_by updated_by INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE acronym CHANGE url url VARCHAR(120) DEFAULT NULL COMMENT \'(DC2Type:string)\'');
        $this->addSql('ALTER TABLE sales_areas CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE country_id country_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE asm_id asm_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE sso_id sso_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE maintenance_contracts_buyer_xus CHANGE maintenance_contract_id maintenance_contract_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE extranet_user_id extranet_user_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE first_article_qualifications_equipment_records CHANGE first_article_qualification_id first_article_qualification_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE equipment_record_id equipment_record_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE maintenance_contracts_equipment_records CHANGE maintenance_contract_id maintenance_contract_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE equipment_record_id equipment_record_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE families CHANGE name name VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE discr discr VARCHAR(20) NOT NULL COMMENT \'(DC2Type:string)\'');
        $this->addSql('ALTER TABLE competitor_pricings_files CHANGE competitor_pricing_id competitor_pricing_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE id id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE first_article_qualifications_plan_items CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE validated_at validated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', CHANGE type_id type_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE first_article_qualification_id first_article_qualification_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE validated_by_id validated_by_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE equipment_hourmeter_resets CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE hourmeter hourmeter INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE created_by created_by INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE equipment_record_id equipment_record_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE equipment_follow_up_reports CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE updated_at updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE hourmeter hourmeter INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE hourmeter_totalizer hourmeter_totalizer INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE odometer odometer INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE created_by created_by INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE updated_by updated_by INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE equipment_record_id equipment_record_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE operational_status_id operational_status_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE equipment_accident_id equipment_accident_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE equipment_maintenance_id equipment_maintenance_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE customer_relationship_teams CHANGE customer_number customer_number VARCHAR(6) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE deleted_at deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', CHANGE task_id task_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE customer_id customer_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE sales_representative_id sales_representative_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE parts_representative_id parts_representative_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE service_representative_id service_representative_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE parts_location_id parts_location_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE service_location_id service_location_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE erp_location_id erp_location_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE equipment_accidents CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE demos_files CHANGE demo_id demo_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE id id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE first_article_qualifications_tags_xref CHANGE first_article_qualification_tag_id first_article_qualification_tag_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE first_article_qualification_id first_article_qualification_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE product_dms CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE dms_type dms_type VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE product_id product_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE dms_id dms_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE product_types CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE english_name english_name VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE french_name french_name VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE spanish_name spanish_name VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE portuguese_name portuguese_name VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE chinese_name chinese_name VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE japanese_name japanese_name VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE german_name german_name VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE russian_name russian_name VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE legacy_id legacy_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE dms_id dms_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE user CHANGE email email VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE firstname firstname VARCHAR(50) NOT NULL COMMENT \'(DC2Type:string)\'');
        $this->addSql('ALTER TABLE freight_forwarders CHANGE emails emails TEXT NOT NULL COMMENT \'(DC2Type:simple_array)\'');
        $this->addSql('ALTER TABLE directory_juridical_location CHANGE address_country address_country VARCHAR(2) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE address_street1 address_street1 VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE address_street2 address_street2 VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE address_postal_code address_postal_code VARCHAR(20) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE address_city address_city VARCHAR(50) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE address_town address_town VARCHAR(50) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE address_state address_state VARCHAR(50) DEFAULT NULL COMMENT \'(DC2Type:string)\'');
        $this->addSql('ALTER TABLE user_setting CHANGE settings settings JSON DEFAULT \'[]\' NOT NULL COMMENT \'(DC2Type:json)\'');
        $this->addSql('ALTER TABLE market_intelligence_competitor CHANGE market_intelligence_id market_intelligence_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE competitor_id competitor_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE user_story CHANGE people_properties people_properties LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\'');
        $this->addSql('ALTER TABLE first_article_qualifications_files CHANGE first_article_qualification_id first_article_qualification_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE id id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE forecast_closures_files CHANGE forecast_closure_id forecast_closure_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE id id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE report_snapshot CHANGE options options JSON NOT NULL COMMENT \'(DC2Type:json)\', CHANGE x_totals x_totals JSON NOT NULL COMMENT \'(DC2Type:json)\', CHANGE y_totals y_totals JSON NOT NULL COMMENT \'(DC2Type:json)\', CHANGE `rows` `rows` JSON NOT NULL COMMENT \'(DC2Type:json)\', CHANGE metadata metadata JSON NOT NULL COMMENT \'(DC2Type:json)\'');
        $this->addSql('ALTER TABLE directory_networks CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE name name VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\'');
        $this->addSql('ALTER TABLE first_article_qualifications_tags CHANGE id id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE first_article_qualifications CHANGE deleted_at deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE supplier_name supplier_name VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE completed_at completed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', CHANGE plan_definition_completed_at plan_definition_completed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', CHANGE eap eap INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE meap meap INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE status status VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE location_id location_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE buyer_id buyer_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE poster_id poster_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE owner_id owner_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE trainings CHANGE starting_at starting_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE ending_at ending_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE manual_prints CHANGE id id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE market_intelligence_files CHANGE market_intelligence_id market_intelligence_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE id id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE demos CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE sso_id sso_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE factory_id factory_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE asm_id asm_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE psm_id psm_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE product_id product_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE customer_id customer_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE country_id country_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE out_of_tolerance_form CHANGE deletedAt deletedAt DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', CHANGE analysisBy analysisBy INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE sales_forecasts_files CHANGE sales_forecast_id sales_forecast_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE id id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE user_story_emails CHANGE people_properties people_properties LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\'');
        $this->addSql('ALTER TABLE maintenance_contracts CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE description description VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE end_user_id end_user_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE buyer_id buyer_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE representative_id representative_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE currencies CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE name name VARCHAR(3) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE legacy_id legacy_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE out_of_tolerance_form_files CHANGE out_of_tolerance_form_id out_of_tolerance_form_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE change_logs CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE hash hash VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE date date DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE message message VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE author_id author_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE market_intelligence CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE legacy_id legacy_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE short_description short_description VARCHAR(75) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE suppliers suppliers LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:simple_array)\', CHANGE poster_id poster_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE equipment_accidents_files CHANGE id id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE unit_operational_statuses CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE name name VARCHAR(3) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE description description VARCHAR(50) NOT NULL COMMENT \'(DC2Type:string)\'');
        $this->addSql('ALTER TABLE product_family_dms CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE dms_type dms_type VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:string)\', CHANGE legacy_id legacy_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE dms_id dms_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE market_intelligence_subscription CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE competitor_id competitor_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE customer_id customer_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE product_type_id product_type_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE subscriber_id subscriber_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE sales_orders_files CHANGE order_id order_id INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE id id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE tool CHANGE status status VARCHAR(25) NOT NULL COMMENT \'(DC2Type:string)\'');
        $this->addSql('ALTER TABLE news CHANGE category_id category_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\', CHANGE people_id people_id INT DEFAULT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE first_article_qualifications_part_numbers CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE revision revision VARCHAR(6) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE description description VARCHAR(255) NOT NULL COMMENT \'(DC2Type:string)\', CHANGE first_article_qualification_id first_article_qualification_id INT NOT NULL COMMENT \'(DC2Type:integer)\'');
        $this->addSql('ALTER TABLE survey_answers CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE value value INT NOT NULL COMMENT \'(DC2Type:integer)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE updated_at updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\'');
    }
}
