bind {{ ansible_default_ipv4.address }}
protected-mode yes
masterauth {{ redis_password }}
requirepass {{ redis_password }}
replicaof {{ redis_master_ip }} 6379
dir /var/lib/redis
logfile "/var/log/redis/redis-server.log"
