services:
    AppBundle\Report\Service\TechnicianOnCall\NumberOpenAndClosedByMonth:
      autoconfigure: true
      autowire: true

    AppBundle\Report\Service\TechnicianOnCall\TechnicianOnCallImmediateRatio:
      autoconfigure: true
      autowire: true

    AppBundle\Report\Service\TechnicianOnCall\TechnicianOnCallAverageTime:
      autoconfigure: true
      autowire: true

    AppBundle\Report\Service\TechnicianOnCall\TechnicianOnCallOldest:
      autoconfigure: true
      autowire: true

    AppBundle\Report\Service\TechnicianOnCall\TechnicianOnCallBacklog:
      autoconfigure: true
      autowire: true

    AppBundle\Report\Service\CustomerServiceRecord\CustomerServiceRecordYearBacklog:
      autoconfigure: true
      autowire: true

    AppBundle\Report\Service\TechnicianOnCall\TechnicianOnCallOperate:
      autoconfigure: true
      autowire: true

    AppBundle\Report\Service\TechnicianOnCall\TechnicianOnCallTroubleshooting:
      autoconfigure: true
      autowire: true

    AppBundle\Report\Service\TechnicianOnCall\TechnicianOnCallSparePartRequest:
      autoconfigure: true
      autowire: true
