export const SUCCESS = "_SUCCESS";
export const FAILED = "_FAILED";
export const RESET = "_RESET";
export const HIDE_SUCCESS_ALERT = "HIDE_SUCCESS_ALERT";
export const HIDE_ERROR_ALERT = "HIDE_ERROR_ALERT";
export const REDIRECT = "REDIRECT";

// Activity actions
export const ACTIVITY_CREATE_COMMENT = "ACTIVITY_CREATE_COMMENT";
export const ACTIVITY_FETCH_LOGS = "ACTIVITY_FETCH_LOGS";
export const ACTIVITY_FETCH_COMMENTS = "ACTIVITY_FETCH_COMMENTS";

// Users constants
export const USER_FETCH_USERS = "USER_FETCH_USERS";
export const USER_FETCH_CONNECTED_USER = "USER_FETCH_CONNECTED_USER";

// Search constants
export const SEARCH_SET_FILTER_TEXT = "SEARCH_SET_FILTER_TEXT";

// ERP constants
export const ERP_FETCH_ITEM = "ERP_FETCH_ITEM";
export const ERP_FETCH_ITEMS = "ERP_FETCH_ITEMS";
export const PART_FETCH_ITEM_MONOLOGISTIC = "PART_FETCH_ITEM_MONOLOGISTIC";
export const PART_FETCH_ITEMS_MONOLOGISTIC = "PART_FETCH_ITEMS_MONOLOGISTIC";
export const ERP_FETCH_BUSINESS_PARTNER = "ERP_FETCH_BUSINESS_PARTNER";
export const ERP_FETCH_BUSINESS_PARTNERS = "ERP_FETCH_BUSINESS_PARTNERS";
export const ERP_FETCH_SUPPLIERS = "ERP_FETCH_SUPPLIERS";

// FAQ
export const FAQ_UPDATE_FAQ = "FAQ_UPDATE_FAQ";
export const FAQ_PLAN_VALIDATION = "FAQ_PLAN_VALIDATION";
export const FIRST_ARTICLE_QUALIFICATION_FETCH_FIRST_ARTICLE_QUALIFICATIONS =
  "FIRST_ARTICLE_QUALIFICATION_FETCH_FIRST_ARTICLE_QUALIFICATIONS";

// ER
export const API_FETCH_ER = "API_FETCH_ER";
export const API_UPDATE_ER = "API_UPDATE_ER";

// Countries
export const API_FETCH_COUNTRY = "API_FETCH_COUNTRY";
export const API_FETCH_COUNTRIES = "API_FETCH_COUNTRIES";

// SFR
export const SFR_UPDATE_SALES_FORECAST = "SFR_UPDATE_SALES_FORECAST";
export const SFR_UPDATE_SALES_FORECASTS = "SFR_UPDATE_SALES_FORECASTS";
export const SFR_GET_SALES_FORECAST_COMMENTS =
  "SFR_GET_SALES_FORECAST_COMMENTS";
export const SFR_UPDATE_SALES_FORECASTS_COMPLETED =
  "SFR_UPDATE_SALES_FORECASTS_COMPLETED";
export const SFR_GET_SALES_FORECAST_VALORIZATION =
  "SFR_GET_SALES_FORECAST_VALORIZATION";
export const SFR_CREATE_MASTER_SALES_FORECAST =
  "SFR_CREATE_MASTER_SALES_FORECAST";

// APC
export const APC_FETCH_AIRPORT = "APC_FETCH_AIRPORT";
export const APC_FETCH_AIRPORTS = "APC_FETCH_AIRPORTS";

// CATALOGUE
export const CATALOGUE_UPDATE_PRODUCT = "CATALOGUE_UPDATE_PRODUCT";
export const CATALOGUE_FETCH_PRODUCTS = "CATALOGUE_FETCH_PRODUCTS";
export const CATALOGUE_FETCH_PRODUCT = "CATALOGUE_FETCH_PRODUCT";
export const CATALOGUE_FETCH_PRODUCT_FAMILIES =
  "CATALOGUE_FETCH_PRODUCT_FAMILIES";

// FINANCE
export const FINANCE_FETCH_FINANCE_FAMILIES = "FINANCE_FETCH_FINANCE_FAMILIES";
export const FINANCE_UPDATE_FINANCE_FAMILY = "FINANCE_UPDATE_FINANCE_FAMILY";
export const FINANCE_HANDLE_FINANCE_FAMILY_FACTORIES =
  "FINANCE_HANDLE_FINANCE_FAMILY_FACTORIES";
export const FINANCE_REMOVE_PRICING = "FINANCE_REMOVE_PRICING";
export const FINANCE_DELETE_FINANCE_FAMILY = "FINANCE_DELETE_FINANCE_FAMILY";
export const FINANCE_CREATE_FINANCE_FAMILY = "FINANCE_CREATE_FINANCE_FAMILY";

// Locations
export const LOCATIONS_FETCH_LOCATIONS = "LOCATIONS_FETCH_LOCATIONS";
export const LOCATION_FETCH_FACTORIES = "LOCATIONS_FETCH_FACTORIES";

// DMS
export const DMS_FETCH_DMS = "DMS_FETCH_DMS";

// ROLE
export const ROLE_FETCH_ROLE = "ROLE_FETCH_ROLE";

// WMS
export const WMS_CREATE_INVENTORY_TRANSFER = "WMS_CREATE_INVENTORY_TRANSFER";
export const WMS_FETCH_ERP_LOCATION = "WMS_FETCH_ERP_LOCATION";
export const WMS_FETCH_ITEM_INVENTORIES = "WMS_FETCH_ITEM_INVENTORIES";
export const WMS_SET_APPLICATION_TITLE = "WMS_SET_APPLICATION_TITLE";
export const WMS_CREATE_STOCK_ADJUSTMENT = "WMS_CREATE_STOCK_ADJUSTMENT";
export const WMS_FETCH_REASON = "WMS_FETCH_REASON";
export const WMS_FETCH_MATERIAL_LISTS = "WMS_FETCH_MATERIAL_LISTS";
export const WMS_FETCH_OUTBOUND_DATA_LIST = "WMS_FETCH_OUTBOUND_DATA_LIST";
export const WMS_CREATE_RELEASE_OUTBOUND = "WMS_CREATE_RELEASE_OUTBOUND";
export const WMS_CREATE_GENERATE_OUTBOUND = "WMS_CREATE_GENERATE_OUTBOUND";
export const WMS_CREATE_GENERATE_MANUAL_OUTBOUND =
  "WMS_CREATE_GENERATE_MANUAL_OUTBOUND";
export const WMS_CREATE_DELETE_OUTBOUND = "WMS_CREATE_DELETE_OUTBOUND";
export const WMS_CREATE_UPDATE_OUTBOUND = "WMS_CREATE_UPDATE_OUTBOUND";
export const WMS_CREATE_UPDATE_RELEASE_OUTBOUND =
  "WMS_CREATE_UPDATE_RELEASE_OUTBOUND";
export const WMS_TOGGLE_PICKING_ALERT = "WMS_TOGGLE_PICKING_ALERT";
export const WMS_CREATE_PICKING_ALERT = "WMS_CREATE_PICKING_ALERT";
export const WMS_TOGGLE_PRINTING_CHOICES = "WMS_TOGGLE_PRINTING_CHOICES";
export const WMS_TOGGLE_PRINTING_PICKING_STICKERS =
  "WMS_TOGGLE_PRINTING_PICKING_STICKERS";
export const WMS_PRINT_PICKING_STICKERS = "WMS_PRINT_PICKING_STICKERS";
export const WMS_TOGGLE_PRINTING_PICKING_BOXES =
  "WMS_TOGGLE_PRINTING_PICKING_BOXES";
export const WMS_PRINT_PICKING_BOXES = "WMS_PRINT_PICKING_BOXES";
export const WMS_CREATE_PICKING_ALERT_NOTIFICATION =
  "WMS_CREATE_PICKING_ALERT_NOTIFICATION";
export const WMS_UPDATE_OUTBOUND_MODE = "WMS_UPDATE_OUTBOUND_MODE";
export const WMS_PICKING_MODE_STEP_BY_STEP = "step_by_step";
export const WMS_PICKING_MODE_BATCH = "batch";
export const WMS_PICKING_ALERT_TYPE_QUANTITY_MISSING = "QTY MISSING";
export const WMS_PICKING_ALERT_TYPE_INCORRECT_QUANTITY = "QTY INCORRECT";
export const WMS_PICKING_ALERT_TYPE_OTHER = "OTHER";
export const WMS_INCREMENT_PICKING_STEP = "WMS_INCREMENT_PICKING_STEP";
export const WMS_RESET_PICKING_STEP = "WMS_RESET_PICKING_STEP";
export const WMS_HANDLE_CYCLE_COUNT_ISSUE = "WMS_HANDLE_CYCLE_COUNT_ISSUE";
export const WMS_QUEUE_CURRENT_STEP = "WMS_QUEUE_CURRENT_STEP";
export const FETCH_STOCK_ADJUSTMENT_WAREHOUSE_LOCATION =
  "FETCH_STOCK_ADJUSTMENT_WAREHOUSE_LOCATION";
export const FETCH_STOCK_ADJUSTMENT_PART_NUMBER =
  "FETCH_STOCK_ADJUSTMENT_PART_NUMBER";
export const WMS_FETCH_ITEM_PIKING_STICKERS = "WMS_FETCH_ITEM_PIKING_STICKERS";

// eCustomer
export const SALES_FETCH_CUSTOMER = "SALES_FETCH_CUSTOMER";
export const SALES_FETCH_CUSTOMERS = "SALES_FETCH_CUSTOMERS";
export const SALES_CLEAR_CUSTOMERS = "SALES_CLEAR_CUSTOMERS";
export const SALES_CREATE_CUSTOMER_FORM = "SALES_CREATE_CUSTOMER_FORM";
export const SALES_UPDATE_CUSTOMER_WATCH_LIST =
  "SALES_UPDATE_CUSTOMER_WATCH_LIST";

// Followers
export const COMMON_FETCH_SUBSCRIPTIONS = "COMMON_FETCH_SUBSCRIPTIONS";
export const COMMON_CREATE_SUBSCRIPTION = "COMMON_CREATE_SUBSCRIPTION";
export const COMMON_DELETE_SUBSCRIPTION = "COMMON_DELETE_SUBSCRIPTION";

// Pinters
export const COMMON_FETCH_PRINTERS = "COMMON_FETCH_PRINTERS";

// Loader
export const COMMON_SET_LOADING = "COMMON_SET_LOADING";

// COMPETITORS
export const COMPETITORS_FETCH_COMPETITOR = "COMPETITORS_FETCH_COMPETITOR";
export const COMPETITORS_FETCH_COMPETITORS = "COMPETITORS_FETCH_COMPETITORS";
export const COMPETITORS_WRITE_COMPETITORS = "COMPETITORS_WRITE_COMPETITORS";

// CPR
export const CPR_WRITE_COMPETITOR_PRICING = "CPR_WRITE_COMPETITOR_PRICING";

// MIM
export const MIM_WRITE_MARKET_INTELLIGENCE = "MIM_WRITE_MARKET_INTELLIGENCE";
export const MIM_WRITE_MARKET_INTELLIGENCE_SUBSCRIPTION =
  "MIM_WRITE_MARKET_INTELLIGENCE_SUBSCRIPTION";
export const MIM_FETCH_MARKET_INTELLIGENCES = "MIM_FETCH_MARKET_INTELLIGENCES";

// Product Manufacturing
export const PRODUCT_MANUFACTURING_CLEAR_DATA =
  "PRODUCT_MANUFACTURING_CLEAR_DATA";
export const PRODUCT_MANUFACTURING_UPDATE_PRODUCT =
  "PRODUCT_MANUFACTURING_UPDATE_PRODUCT";

// USER STORY
export const FETCH_USER_STORY_DETAIL_REQUEST =
  "FETCH_USER_STORY_DETAIL_REQUEST";
export const USER_STORY_WRITE = "USER_STORY_WRITE";
export const USER_STORY_EDIT = "USER_STORY_EDIT";
export const USER_STORIES_GET = "USER_STORIES_GET";
export const USER_STORY_GET = "USER_STORY_GET";
export const USER_STORY_DELETE = "USER_STORY_DELETE";
export const SPECIFICATION_GET = "SPECIFICATION_GET";
export const SPECIFICATION_UPDATE_STATUS = "SPECIFICATION_UPDATE_STATUS";
export const USER_STORY_UPDATE_STATUS = "USER_STORY_UPDATE_STATUS";
export const USER_STORY_RESET = "USER_STORY_STATUS_RESET";
export const USER_STORY_TOGGLE_SHOW_LIST = "USER_STORY_TOGGLE_SHOW_LIST";
export const USER_STORY_TOGGLE_CREATION_FORM =
  "USER_STORY_TOGGLE_CREATION_FORM";
export const USER_STORY_TOGGLE_EDIT_FORM = "USER_STORY_TOGGLE_EDIT_FORM";
export const USER_STORY_CLOSE_FORM = "USER_STORY_CLOSE_FORM";

export const USER_STORY_DUPLICATE = "USER_STORY_DUPLICATE";
// Business Units
export const DIRECTORY_FETCH_BUSINESS_UNITS = "DIRECTORY_FETCH_BUSINESS_UNITS";

// Extranet Users
export const EXTRANET_USER_FETCH_EXTRANET_USERS =
  "EXTRANET_USER_FETCH_EXTRANET_USERS";
export const EXTRANET_USER_CREATE_EXTRANET_USER_ACLS =
  "EXTRANET_USER_CREATE_EXTRANET_USER_ACLS";

// SPR
export const SPR_FETCH_ITEMS = "SPR_FETCH_ITEMS";
export const SPR_FETCH_ITEM = "SPR_FETCH_ITEM";
export const SPR_FETCH_DELIVERY_ADDRESSES = "SPR_FETCH_DELIVERY_ADDRESSES";
export const SPR_FETCH_AIRPORT = "SPR_FETCH_AIRPORT";
export const SPR_FETCH_CONTACT = "SPR_FETCH_CONTACT";
export const SPR_CREATE_TOC_SPARE_PARTS_REQUEST =
  "SPR_CREATE_TOC_SPARE_PARTS_REQUEST";
export const SPR_EDIT_TOC_SPARE_PARTS_REQUEST =
  "SPR_EDIT_TOC_SPARE_PARTS_REQUEST";
export const SPR_CREATE_SB_SPARE_PARTS_REQUEST =
  "SPR_CREATE_SB_SPARE_PARTS_REQUEST";
export const SPR_EDIT_SPARE_PARTS_REQUEST_ADDRESS =
  "SPR_EDIT_SPARE_PARTS_REQUEST_ADDRESS";

// Customer ERP References
export const SALES_CRT_FETCH_CUSTOMER = "SALES_CRT_FETCH_CUSTOMER";

// CRT
export const SALES_CREATE_CUSTOMER_RELATIONSHIP_TEAM =
  "SALES_CREATE_CUSTOMER_RELATIONSHIP_TEAM";
export const SALES_EDIT_CUSTOMER_RELATIONSHIP_TEAM =
  "SALES_EDIT_CUSTOMER_RELATIONSHIP_TEAM";

// PART
export const PART_FETCH_ITEMS = "PART_FETCH_ITEMS";
export const PART_FETCH_ITEM = "PART_FETCH_ITEM";
export const PART_EDIT_PART_OBJECT = "PART_EDIT_PART_OBJECT";

// NON CONFORMITY
export const NON_CONFORMITY_FETCH_NON_CONFORMITIES =
  "NON_CONFORMITY_FETCH_NON_CONFORMITIES";

// MIS
export const MIS_FETCH_MODULES = "MIS_FETCH_MODULES";
export const MIS_FETCH_MODULE = "MIS_FETCH_MODULE";
export const MIS_FETCH_TYPES = "MIS_FETCH_TYPES";
export const MIS_FETCH_TYPE = "MIS_FETCH_TYPE";
export const MIS_UPDATE_TROUBLE_TICKET = "MIS_UPDATE_TROUBLE_TICKET";
export const MIS_FETCH_SUBSCRIPTIONS = "MIS_FETCH_SUBSCRIPTIONS";
export const MIS_UPDATE_TROUBLE_TICKET_OWNERS =
  "MIS_UPDATE_TROUBLE_TICKET_OWNERS";
export const WRITE_PRE_DELIVERY_INSPECTION = "WRITE_PRE_DELIVERY_INSPECTION";
export const PRE_DELIVERY_INSPECTION_STATUS_UPDATE =
  "PRE_DELIVERY_INSPECTION_STATUS_UPDATE";
export const MIS_GET_TROUBLE_TICKETS_BY_MODULE =
  "MIS_GET_TROUBLE_TICKETS_BY_MODULE";
export const MIS_ADD_TROUBLE_TICKETS_TO_USER_STORIES =
  "MIS_ADD_TROUBLE_TICKETS_TO_USER_STORIES";
export const MIS_TROUBLE_TICKETS_RESET = "MIS_TROUBLE_TICKETS_RESET";

export const MIS_CREATE_PROJECT = "MIS_CREATE_PROJECT";
export const MIS_EDIT_PROJECT = "MIS_EDIT_PROJECT";

export const MIS_FETCH_TAGS = "MIS_FETCH_TAGS";
export const MIS_UPDATE_SUPPORT_TEAM = "MIS_UPDATE_SUPPORT_TEAM";
export const MIS_CREATE_SUPPORT_TEAM = "MIS_CREATE_SUPPORT_TEAM";

// INCOTERMS
export const INCOTERM_FETCH_TERMS_OF_DELIVERIES =
  "INCOTERM_FETCH_TERMS_OF_DELIVERIES";

// CURRENCY
export const CURRENCY_FETCH_CURRENCIES = "CURRENCY_FETCH_CURRENCIES";

// EVENTS
export const EVENT_ADD_EVENT = "EVENT_ADD_EVENT";
export const EVENT_UPDATE_EVENT = "EVENT_UPDATE_EVENT";
// TASK
export const CREATE_TASK = "CREATE_TASK";
export const EDIT_TASK = "EDIT_TASK";

// Technician On Call (TOC)
export const TAG_FETCH_LIST = "TAG_FETCH_LIST";

// LINTER
export const LINTER_REPORT_FILENAME = "eslint-report.json";
export const LINTER_BASELINE_FILENAME = "eslint-baseline.json";
export const LINTER_BASELINE_REPORT_FILENAME = "eslint-baseline-report.json";

// SUPPLIER_CORRECTIVE_ACTION_REQUEST
export const CREATE_SUPPLIER_CORRECTIVE_ACTION_REQUEST =
  "CREATE_SUPPLIER_CORRECTIVE_ACTION_REQUEST";
export const UPDATE_SUPPLIER_CORRECTIVE_ACTION_REQUEST =
  "UPDATE_SUPPLIER_CORRECTIVE_ACTION_REQUEST";

// TOC Status Strings
export const TOC_STATUS_MAP: { [key: string]: string } = {
  PENDING: "Pending",
  IN_PROGRESS: "In Progress",
  SUSPENDED: "Suspended",
  SOLVED: "Solved",
  CLOSED: "Closed",
};

// TOC Status
export const TOC_STATUS = {
  PENDING: "PENDING",
  IN_PROGRESS: "IN_PROGRESS",
  SUSPENDED: "SUSPENDED",
  SOLVED: "SOLVED",
  CLOSED: "CLOSED",
} as const;
