<?xml version="1.0"?>
<wsdl:definitions
	xmlns:bo="http://www.infor.com/businessinterface/HoursAccounting_TLD"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.infor.com/businessinterface/HoursAccounting_TLD"
	name="HoursAccounting_TLD">
	<wsdl:types>
		<xsd:schema
			targetNamespace="http://www.infor.com/businessinterface/HoursAccounting_TLD">
			<xsd:complexType
				name="PostHoursRequestType">
				<xsd:sequence>
					<xsd:element
						name="ControlArea"
						minOccurs="0">
						<xsd:complexType>
							<xsd:sequence>
								<xsd:element
									name="processingScope"
									type="bo:processingScope"
									default="request"
									minOccurs="0"
								/>
								<xsd:element
									name="SuppressNillable"
									type="xsd:boolean"
									minOccurs="0"
								/>
							</xsd:sequence>
						</xsd:complexType>
					</xsd:element>
					<xsd:element
						name="DataArea"
						minOccurs="0">
						<xsd:complexType>
							<xsd:sequence>
								<xsd:element
									name="HoursAccounting_TLD"
									minOccurs="0"
									maxOccurs="unbounded">
									<xsd:complexType>
										<xsd:sequence>
											<xsd:element
												name="Employee"
												type="bo:tcemno_mandatory"
												minOccurs="1"
											/>
											<xsd:element
												name="Transaction"
												type="bo:tcmcs.st15m"
												minOccurs="0"
											/>
											<xsd:element
												name="Task"
												type="bo:tcmcs.st15m"
												minOccurs="0"
											/>
											<xsd:element
												name="ProductionOrder"
												type="bo:tcmcs.st10m"
												minOccurs="0"
											/>
											<xsd:element
												name="Operation"
												type="xsd:integer"
												minOccurs="0"
											/>
											<xsd:element
												name="Text"
												type="xsd:anyType"
												minOccurs="0"
												maxOccurs="unbounded"
											/>
											<xsd:element
												name="TransactionDate"
												type="bo:tcmcs.str25"
												minOccurs="0"
											/>
											<xsd:element
												name="TransactionTime"
												type="bo:tcmcs.str25"
												minOccurs="0"
											/>
										</xsd:sequence>
									</xsd:complexType>
								</xsd:element>
							</xsd:sequence>
						</xsd:complexType>
					</xsd:element>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType
				name="PostHoursResponseType">
				<xsd:sequence>
					<xsd:element
						name="DataArea"
						minOccurs="0">
						<xsd:complexType>
							<xsd:sequence>
								<xsd:element
									name="HoursAccounting_TLD"
									minOccurs="0"
									maxOccurs="unbounded">
									<xsd:complexType>
										<xsd:sequence>
											<xsd:element
												name="Employee"
												type="bo:tcemno_mandatory"
												minOccurs="1"
											/>
											<xsd:element
												name="Transaction"
												type="bo:tcmcs.st15m"
												minOccurs="0"
											/>
											<xsd:element
												name="Task"
												type="bo:tcmcs.st15m"
												minOccurs="0"
											/>
											<xsd:element
												name="ProductionOrder"
												type="bo:tcmcs.st10m"
												minOccurs="0"
											/>
											<xsd:element
												name="Operation"
												type="xsd:integer"
												minOccurs="0"
											/>
											<xsd:element
												name="Text"
												type="xsd:anyType"
												minOccurs="0"
												maxOccurs="unbounded"
											/>
											<xsd:element
												name="TransactionDate"
												type="bo:tcmcs.str25"
												minOccurs="0"
											/>
											<xsd:element
												name="TransactionTime"
												type="bo:tcmcs.str25"
												minOccurs="0"
											/>
										</xsd:sequence>
									</xsd:complexType>
								</xsd:element>
							</xsd:sequence>
						</xsd:complexType>
					</xsd:element>
					<xsd:element
						name="InformationArea"
						type="bo:InformationArea"
						minOccurs="0"
					/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType
				name="ActivationType">
				<xsd:sequence>
					<xsd:element
						name="username"
						type="xsd:string"
						minOccurs="0"
					/>
					<xsd:element
						name="password"
						type="xsd:string"
						minOccurs="0"
					/>
					<xsd:element
						name="company"
						type="xsd:int"
						minOccurs="0"
					/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:element
				name="Activation"
				type="bo:ActivationType"
			/>
			<xsd:element
				name="Result"
				type="bo:Message"
			/>
			<xsd:complexType
				name="InformationArea">
				<xsd:sequence>
					<xsd:element
						name="Message"
						maxOccurs="unbounded"
						type="bo:InformationMessage"
					/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType
				name="Message">
				<xsd:sequence>
					<xsd:element
						name="messageIndex"
						type="xsd:integer"
						minOccurs="0"
					/>
					<xsd:element
						name="messageCode"
						type="xsd:string"
					/>
					<xsd:element
						name="messageType">
						<xsd:simpleType>
							<xsd:restriction
								base="xsd:string">
								<xsd:enumeration
									value="Error"
								/>
								<xsd:enumeration
									value="Warning"
								/>
								<xsd:enumeration
									value="Information"
								/>
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:element
						name="messageText"
						type="xsd:string"
					/>
					<xsd:element
						name="messageSource"
						type="xsd:string"
					/>
					<xsd:element
						name="MessageDetails"
						minOccurs="0">
						<xsd:complexType>
							<xsd:sequence>
								<xsd:element
									name="Message"
									maxOccurs="unbounded"
									type="bo:DetailMessage"
								/>
							</xsd:sequence>
						</xsd:complexType>
					</xsd:element>
					<xsd:element
						name="messageCorrectiveAction"
						type="xsd:string"
						minOccurs="0"
					/>
					<xsd:choice>
						<xsd:element
							name="messageAdditionalHelpText"
							type="xsd:string"
							minOccurs="0"
						/>
						<xsd:element
							name="messageAdditionalHelpURI"
							type="xsd:anyURI"
							minOccurs="0"
						/>
					</xsd:choice>
					<xsd:element
						name="MessageReference"
						minOccurs="0">
						<xsd:complexType>
							<xsd:sequence>
								<xsd:element
									name="messageReferenceType"
									type="xsd:string"
								/>
								<xsd:element
									name="messageReferenceInfo"
									type="xsd:anyType"
								/>
							</xsd:sequence>
						</xsd:complexType>
					</xsd:element>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType
				name="DetailMessage">
				<xsd:complexContent>
					<xsd:extension
						base="bo:Message">
						<xsd:attribute
							name="ID"
							type="xsd:ID"
							use="optional"
						/>
					</xsd:extension>
				</xsd:complexContent>
			</xsd:complexType>
			<xsd:complexType
				name="InformationMessage">
				<xsd:complexContent>
					<xsd:extension
						base="bo:Message">
						<xsd:attribute
							name="ID"
							type="xsd:ID"
							use="required"
						/>
					</xsd:extension>
				</xsd:complexContent>
			</xsd:complexType>
			<xsd:complexType
				name="FilterType">
				<xsd:choice>
					<xsd:element
						name="LogicalExpression"
						type="bo:LogicalExpressionType"
					/>
					<xsd:element
						name="ComparisonExpression"
						type="bo:ComparisonExpressionType"
					/>
				</xsd:choice>
			</xsd:complexType>
			<xsd:complexType
				name="LogicalExpressionType">
				<xsd:sequence>
					<xsd:element
						name="logicalOperator">
						<xsd:simpleType>
							<xsd:restriction
								base="xsd:string">
								<xsd:enumeration
									value="or"
								/>
								<xsd:enumeration
									value="and"
								/>
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:choice
						minOccurs="2"
						maxOccurs="unbounded">
						<xsd:element
							maxOccurs="unbounded"
							name="LogicalExpression"
							type="bo:LogicalExpressionType"
						/>
						<xsd:element
							maxOccurs="unbounded"
							name="ComparisonExpression"
							type="bo:ComparisonExpressionType"
						/>
					</xsd:choice>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType
				name="ComparisonExpressionType">
				<xsd:sequence>
					<xsd:element
						name="comparisonOperator">
						<xsd:simpleType>
							<xsd:restriction
								base="xsd:string">
								<xsd:enumeration
									value="le"
								/>
								<xsd:enumeration
									value="lt"
								/>
								<xsd:enumeration
									value="ge"
								/>
								<xsd:enumeration
									value="gt"
								/>
								<xsd:enumeration
									value="ne"
								/>
								<xsd:enumeration
									value="eq"
								/>
								<xsd:enumeration
									value="like"
								/>
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:choice>
						<xsd:element
							name="attributeName"
							type="bo:filterAttributeListDT"
						/>
						<xsd:element
							name="emptyValue"
							type="bo:EmptyValueType"
						/>
						<xsd:element
							name="instanceValue"
							type="xsd:string"
						/>
					</xsd:choice>
					<xsd:choice>
						<xsd:element
							name="attributeName"
							type="bo:filterAttributeListDT"
						/>
						<xsd:element
							name="emptyValue"
							type="bo:EmptyValueType"
						/>
						<xsd:element
							name="instanceValue"
							type="xsd:string"
						/>
					</xsd:choice>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType
				name="EmptyValueType"
			/>
			<xsd:simpleType
				name="filterAttributeListDT">
				<xsd:restriction
					base="xsd:string">
					<xsd:enumeration
						value="HoursAccounting_TLD.Employee"
					/>
					<xsd:enumeration
						value="HoursAccounting_TLD.Transaction"
					/>
					<xsd:enumeration
						value="HoursAccounting_TLD.Task"
					/>
					<xsd:enumeration
						value="HoursAccounting_TLD.ProductionOrder"
					/>
					<xsd:enumeration
						value="HoursAccounting_TLD.Operation"
					/>
					<xsd:enumeration
						value="HoursAccounting_TLD.Text"
					/>
					<xsd:enumeration
						value="HoursAccounting_TLD.TransactionDate"
					/>
					<xsd:enumeration
						value="HoursAccounting_TLD.TransactionTime"
					/>
				</xsd:restriction>
			</xsd:simpleType>
			<xsd:complexType
				name="SelectionType">
				<xsd:sequence>
					<xsd:element
						name="selectionAttribute"
						maxOccurs="unbounded">
						<xsd:simpleType>
							<xsd:restriction
								base="xsd:string">
								<xsd:enumeration
									value="*"
								/>
								<xsd:enumeration
									value="HoursAccounting_TLD.*"
								/>
								<xsd:enumeration
									value="HoursAccounting_TLD.Employee"
								/>
								<xsd:enumeration
									value="HoursAccounting_TLD.Transaction"
								/>
								<xsd:enumeration
									value="HoursAccounting_TLD.Task"
								/>
								<xsd:enumeration
									value="HoursAccounting_TLD.ProductionOrder"
								/>
								<xsd:enumeration
									value="HoursAccounting_TLD.Operation"
								/>
								<xsd:enumeration
									value="HoursAccounting_TLD.Text"
								/>
								<xsd:enumeration
									value="HoursAccounting_TLD.TransactionDate"
								/>
								<xsd:enumeration
									value="HoursAccounting_TLD.TransactionTime"
								/>
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:simpleType
				name="processingScope">
				<xsd:restriction
					base="xsd:string">
					<xsd:enumeration
						value="not_applicable"
					/>
					<xsd:enumeration
						value="request"
					/>
					<xsd:enumeration
						value="business_entity"
					/>
					<xsd:enumeration
						value="business_entity_component"
					/>
				</xsd:restriction>
			</xsd:simpleType>
			<xsd:simpleType
				name="actionType">
				<xsd:restriction
					base="xsd:string">
					<xsd:enumeration
						value="create"
					/>
					<xsd:enumeration
						value="createOrChange"
					/>
					<xsd:enumeration
						value="change"
					/>
					<xsd:enumeration
						value="delete"
					/>
					<xsd:enumeration
						value="unchanged"
					/>
				</xsd:restriction>
			</xsd:simpleType>
			<xsd:simpleType
				name="tcemno_mandatory">
				<xsd:restriction
					base="xsd:string">
					<xsd:maxLength
						value="9"
					/>
					<xsd:minLength
						value="1"
					/>
				</xsd:restriction>
			</xsd:simpleType>
			<xsd:simpleType
				name="tcmcs.st15m">
				<xsd:restriction
					base="xsd:string">
					<xsd:maxLength
						value="60"
					/>
				</xsd:restriction>
			</xsd:simpleType>
			<xsd:simpleType
				name="tcmcs.st10m">
				<xsd:restriction
					base="xsd:string">
					<xsd:maxLength
						value="10"
					/>
				</xsd:restriction>
			</xsd:simpleType>
			<xsd:simpleType
				name="tcmcs.str25">
				<xsd:restriction
					base="xsd:string">
					<xsd:maxLength
						value="25"
					/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message
		name="PostHoursRequest">
		<wsdl:part
			name="PostHoursRequest"
			type="bo:PostHoursRequestType"
		/>
	</wsdl:message>
	<wsdl:message
		name="PostHoursResponse">
		<wsdl:part
			name="PostHoursResponse"
			type="bo:PostHoursResponseType"
		/>
	</wsdl:message>
	<wsdl:message
		name="Result">
		<wsdl:part
			name="Result"
			element="bo:Result"
		/>
	</wsdl:message>
	<wsdl:message
		name="Header">
		<wsdl:part
			name="Activation"
			element="bo:Activation"
		/>
	</wsdl:message>
	<wsdl:portType
		name="HoursAccounting_TLD">
		<wsdl:operation
			name="PostHours">
			<wsdl:input
				message="bo:PostHoursRequest"
			/>
			<wsdl:output
				message="bo:PostHoursResponse"
			/>
			<wsdl:fault
				name="FaultName"
				message="bo:Result"
			/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding
		name="HoursAccounting_TLDSoapBinding"
		type="bo:HoursAccounting_TLD">
		<soap:binding
			style="rpc"
			transport="http://schemas.xmlsoap.org/soap/http"
		/>
		<wsdl:operation
			name="PostHours">
			<soap:operation
				soapAction=""
			/>
			<wsdl:input>
				<soap:body
					use="literal"
					namespace="http://www.infor.com/businessinterface/HoursAccounting_TLD"
				/>
				<soap:header
					message="bo:Header"
					part="Activation"
					use="literal"
				/>
			</wsdl:input>
			<wsdl:output>
				<soap:body
					use="literal"
					namespace="http://www.infor.com/businessinterface/HoursAccounting_TLD"
				/>
			</wsdl:output>
			<wsdl:fault
				name="FaultName">
				<soap:fault
					name="FaultName"
					use="literal"
				/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service
		name="HoursAccounting_TLDService">
		<wsdl:port
			name="HoursAccounting_TLDSoapPort"
			binding="bo:HoursAccounting_TLDSoapBinding">
			<soap:address location="https://mingle-ionapi.eu1.inforcloudsuite.com/TLD_TST/LN/c4ws/services/HoursAccounting_TLD/%7BContext%7D"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
