import { IElement } from "../components/SvgGenerator/lib/types/IElement";
import { IGroupElement } from "../components/SvgGenerator/lib/types/IGroupElement";

export const ELEMENT_ID = {
  mfgLocation: "mfg-location",
  model: "model",
  mfgDate: "mfg-date",
  serialNumber: "serial-number",
  unladenWeightKg: "unladen-weight-kg",
  unladenWeightLbs: "unladen-weight-lbs",
  ratedPowerKw: "rated-power-kw",
  ratedPowerHp: "rated-power-hp",
  qrCode: "qr-code",
  logo: "logo",
  ceLogo: "ce-logo",
};

export const SVG_DRAWING: IGroupElement = {
  type: "Group",
  name: "root",
  x: 0,
  y: 0,
  elements: [
    { type: "Rectangle", x: 0, y: 0, width: 80, height: 100, radius: 4 },
    { type: "Line", startX: 0, startY: 30, endX: 80, endY: 30.4 },
    { type: "Line", startX: 0, startY: 30.5, endX: 80, endY: 31 },
    {
      id: ELEMENT_ID.mfgLocation,
      type: "Field",
      field: {
        x: 23,
        y: 33,
        width: 30,
        height: 7,
      },
      leftContent: {
        text: "MFG LOCATION",
        fontSize: 2.9,
        adjustY: 0.3,
      },
      rightContent: {
        text: "USINE DE PRODUCTION",
        fontSize: 2.56,
      },
    },
    {
      id: ELEMENT_ID.model,
      type: "Field",
      field: {
        x: 23,
        y: 41.5,
        width: 30,
        height: 7,
      },
      leftContent: {
        text: "MODEL",
        fontSize: 2.9,
        adjustY: 0.3,
      },
      rightContent: {
        text: "TYPE",
        fontSize: 2.8,
        adjustY: 0.3,
      },
    },
    {
      id: ELEMENT_ID.mfgDate,
      type: "Field",
      field: {
        x: 23,
        y: 50,
        width: 30,
        height: 7,
      },
      leftContent: {
        text: "MFG DATE",
        fontSize: 2.9,
        adjustY: 0.3,
      },
      rightContent: {
        text: "DATE DE FABRICATION",
        fontSize: 2.7,
        adjustY: 0.6,
      },
    },
    {
      id: ELEMENT_ID.serialNumber,
      type: "Field",
      field: {
        x: 23,
        y: 58.5,
        width: 30,
        height: 7,
      },
      leftContent: {
        text: "SERIAL NUMBER",
        fontSize: 2.75,
        adjustY: 0.5,
      },
      rightContent: {
        text: "NUMERO DE SERIE",
        fontSize: 2.8,
        adjustY: 0.4,
      },
    },
    {
      type: "Field",
      field: {
        x: 23,
        y: 67,
        width: 30,
        height: 7,
      },
      leftContent: {
        text: "UNLADEN WEIGHT",
        fontSize: 2.77,
        adjustY: 0.3,
      },
      rightContent: {
        text: "MASSE A VIDE",
        fontSize: 2.77,
        adjustY: 0.3,
      },
    },
    {
      type: "Field",
      field: {
        x: 23,
        y: 75.5,
        width: 30,
        height: 7,
      },
      leftContent: {
        text: "RATED POWER",
        fontSize: 2.85,
        adjustY: 0.3,
      },
      rightContent: {
        text: "PUISSANCE NOMINALE",
        fontSize: 2.65,
        adjustY: 0.6,
      },
    },
    {
      id: ELEMENT_ID.qrCode,
      type: "Image",
      x: 45,
      y: 3,
      height: 25,
      width: 25,
    },
    {
      type: "TextInRectangle",
      x: 32.75,
      y: 67,
      height: 7,
      width: 30,
      text: "KG/LBS",
      fontSize: 2.85,
      alignHorizontally: true,
      alignVertically: true,
      fontWeight: "bold",
      adjustY: 0.3,
    },
    {
      type: "TextInRectangle",
      x: 32,
      y: 75.5,
      height: 7,
      width: 30,
      text: "KW/HP",
      fontSize: 2.85,
      alignHorizontally: true,
      alignVertically: true,
      fontWeight: "bold",
      adjustY: 0.3,
    },
    {
      type: "TextInRectangle",
      x: 18.3,
      y: 67,
      height: 7,
      width: 30,
      text: "/",
      fontSize: 2.85,
      alignHorizontally: true,
      alignVertically: true,
      fontWeight: "bold",
      adjustY: 0.3,
    },
    {
      type: "TextInRectangle",
      x: 18.3,
      y: 75.5,
      height: 7,
      width: 30,
      text: "/",
      fontSize: 2.85,
      alignHorizontally: true,
      alignVertically: true,
      fontWeight: "bold",
      adjustY: 0.3,
    },
    {
      id: ELEMENT_ID.unladenWeightKg,
      type: "TextInRectangle",
      x: 23.3,
      y: 67,
      height: 7,
      width: 9.4,
      text: "",
      fontSize: 2.85,
      alignHorizontally: true,
      alignVertically: true,
      fontWeight: "bold",
      adjustY: 0.3,
    },
    {
      id: ELEMENT_ID.unladenWeightLbs,
      type: "TextInRectangle",
      x: 33.8,
      y: 67,
      height: 7,
      width: 9.4,
      text: "",
      fontSize: 2.85,
      alignHorizontally: true,
      alignVertically: true,
      fontWeight: "bold",
      adjustY: 0.3,
    },
    {
      id: ELEMENT_ID.ratedPowerKw,
      type: "TextInRectangle",
      x: 23.3,
      y: 75.5,
      height: 7,
      width: 9.4,
      text: "",
      fontSize: 2.85,
      alignHorizontally: true,
      alignVertically: true,
      fontWeight: "bold",
      adjustY: 0.3,
    },
    {
      id: ELEMENT_ID.ratedPowerHp,
      type: "TextInRectangle",
      x: 33.8,
      y: 75.5,
      height: 7,
      width: 9.4,
      text: "",
      fontSize: 2.85,
      alignHorizontally: true,
      alignVertically: true,
      fontWeight: "bold",
      adjustY: 0.3,
    },
  ],
};

export const TLD_ELEMENTS: Array<IElement> = [
  {
    id: ELEMENT_ID.logo,
    type: "Image",
    x: 10.5,
    y: 4.7,
    height: 12,
    width: 24,
  },
  {
    type: "TextInRectangle",
    x: 9.7,
    y: 15.5,
    height: 10,
    width: 25,
    text: "Services / Parts / Enquiry",
    fontSize: 2.65,
    alignHorizontally: true,
    alignVertically: true,
    textCenter: true,
    fontWeight: "bold",
  },
  {
    type: "TextInRectangle",
    x: 9.5,
    y: 19.2,
    height: 10,
    width: 25,
    text: "www.tld-group.com",
    fontSize: 2.75,
    alignHorizontally: true,
    alignVertically: true,
    textCenter: true,
    fontWeight: "bold",
  },
  {
    type: "TextInRectangle",
    x: 6.2,
    y: 80.5,
    height: 17.5,
    width: 52,
    text: "This equipment is subject to a retention",
    fontSize: 3.48,
    alignHorizontally: true,
    alignVertically: true,
    fontWeight: "bold",
  },
  {
    type: "TextInRectangle",
    x: 6,
    y: 85.2,
    height: 17.5,
    width: 52,
    text: "of title clause until full payment to TLD.",
    fontSize: 3.44,
    alignHorizontally: true,
    alignVertically: true,
    fontWeight: "bold",
  },
];

export const AERO_ELEMENTS: Array<IElement> = [
  {
    id: ELEMENT_ID.logo,
    type: "Image",
    x: 3.8,
    y: 4.7,
    height: 11,
    width: 37.5,
  },
  {
    type: "TextInRectangle",
    x: 9.7,
    y: 15.5,
    height: 10,
    width: 25,
    text: "Services / Parts / Enquiry",
    fontSize: 2.65,
    alignHorizontally: true,
    alignVertically: true,
    textCenter: true,
    fontWeight: "bold",
  },
  {
    type: "TextInRectangle",
    x: 9.8,
    y: 19,
    height: 10,
    width: 25,
    text: "www.aerospecialties.com",
    fontSize: 2.375,
    alignHorizontally: true,
    alignVertically: true,
    textCenter: true,
    fontWeight: "bold",
  },
  {
    type: "TextInRectangle",
    x: 6.3,
    y: 80.7,
    height: 17.5,
    width: 52,
    text: "This equipment is subject to a retention of title",
    fontSize: 2.97,
    alignHorizontally: true,
    alignVertically: true,
    fontWeight: "bold",
  },
  {
    type: "TextInRectangle",
    x: 6.1,
    y: 85.2,
    height: 17.5,
    width: 52,
    text: "clause until full payment to AERO Specialties.",
    fontSize: 3.06,
    alignHorizontally: true,
    alignVertically: true,
    fontWeight: "bold",
  },
];

export const CE_ELEMENT: IElement = {
  type: "CE",
  x: 70.5,
  y: 90,
  id: ELEMENT_ID.ceLogo,
};
