- src: geerlingguy.nodejs
  version: 7.1.0
- src: geerlingguy.php
  version: 6.1.0
- src: geerlingguy.php-mysql
  version: 2.1.0
- src: geerlingguy.php-versions
  version: 7.0.1
- src: geerlingguy.nginx
  version: 3.1.1
- src: geerlingguy.ntp
  version: 2.3.1
- src: geerlingguy.apache
  version: 3.3.0
- src: geerlingguy.apache-php-fpm
  version: 1.1.0
