supervisor_started: true
supervisor_enabled: true
supervisor_config_path: /etc/supervisor
supervisor_log_dir: /var/log/supervisor
supervisor_programs: []
supervisor_unix_http_server_enable: true
supervisor_unix_http_server_socket_path: /var/run/supervisor.sock
supervisor_unix_http_server_password_protect: false
supervisor_unix_http_server_username: ""
supervisor_unix_http_server_password: ""
