port 26379
sentinel monitor alvest_redis_ha {{ redis_master_ip }} 6379 2
sentinel down-after-milliseconds alvest_redis_ha 5000
sentinel failover-timeout alvest_redis_ha 60000
sentinel parallel-syncs alvest_redis_ha 1
sentinel auth-pass alvest_redis_ha {{ redis_password }}
logfile "/var/log/redis/redis-sentinel.log"
