[program:messenger-consume]
command=/bin/bash -c 'source "$0" && exec "$@"' .symfony php current/bin/console messenger:consume async --time-limit=3600 --memory-limit=128M --limit=100
directory=/var/www/api.tld-group.com/
user=apiuser
numprocs=2
autostart=true
autorestart=true
process_name=%(program_name)s_%(process_num)02d
