- name: Playbook for web portals servers
  hosts: portals
  roles:
    - { role: shared-handlers, tags: [always] }
    - { role: monitored-server, tags: [monitoring] }
    - { role: iptables, tags: [security], vars: { iptables_rules_template: templates/portals/iptables/rules.v4.j2 }}
    - { role: utils, tags: [utils] }
    - { role: locales, tags: [locales] }
    - { role: code-host, tags: [web] }
    - { role: cron, tags: [cron] }
    - { role: crontab-legacy, tags: [cron] }
    - { role: redis-replica, tags: [redis] }
    - { role: git, tags: [web] }
    - { role: pdf, tags: [pdf] }
    - { role: geerlingguy.nodejs, become: true, tags: [web, js], vars: { ansible_distribution_release: impish }} # noqa var-naming[no-role-prefix]
    - { role: geerlingguy.php-versions, become: true, tags: [web, php, env] }
    - { role: geerlingguy.php-mysql, become: true, tags: [web, php, env] }
    - { role: geerlingguy.php, become: true, tags: [web, php, env] }
    - { role: geerlingguy.apache, become: true, tags: [web, apache] }
    - { role: geerlingguy.apache-php-fpm, become: true, tags: [web, apache, php] }
    - { role: logrotate, become: true, tags: [php] }
    - { role: geerlingguy.ntp, become: true, tags: [utils] }
    - { role: mail, become: true, tags: [mail] }
    -
      role: dotenv
      tags: [env]
      vars:
        dotenv_template: "templates/portals/dms/.env.j2"
        dotenv_path: "{{ monorepo_path }}/shared/dms/.env"
        dotenv_profile_filename: dms_env
    -
      role: dotenv
      tags: [env]
      vars:
        dotenv_template: "templates/portals/intranet/.env.j2"
        dotenv_path: "{{ monorepo_path }}/shared/intranet/.env"
        dotenv_profile_filename: intranet_env
    -
      role: dotenv
      tags: [env]
      vars:
        dotenv_template: "templates/portals/shopfloor/.env.j2"
        dotenv_path: "{{ monorepo_path }}/shared/shopfloor/.env"
        dotenv_profile_filename: shopfloor_env
    - { role: jwt, tags: [jwt], vars: { jwt_directory: "{{ monorepo_path }}/shared/intranet/config/jwt" } }
    - { role: mount, tags: [mount] }
    - { role: legacy, tags: [legacy] }
    - { role: owncloud-client, tags: [owncloud] }
    - { role: sentinel, tags: [sentinel] }
    - { role: auditbeat, tags: [auditbeat] }
    - { role: landscape, tags: [landscape] }
