all:
  vars:
    ansible_user: ansible
    alvest_api_url: api.alvest.fr
    powerbi_url: powerbi.alvest.fr

api:
  hosts:
    web-api-01.tld-america.com:

evendors:
  hosts:
    web-evendors-01.tld-america.com:

extranet:
  hosts:
    web-extranet-01.tld-america.com:

mobile:
  hosts:
    web-mobile-01.tld-america.com:

portals:
  hosts:
    web-portals-01.tld-america.com:
    web-portals-02.tld-america.com:

powerbi:
  hosts:
    web-powerbi-01.tld-america.com: