all:
  vars:
    ansible_user: ansible
    alvest_api_url: test-api.alvest.fr
    powerbi_url: test-powerbi.alvest.fr

api:
  hosts:
    web-stag-api-01.tld-america.com:

evendors:
  hosts:
    web-stag-evendors-01.tld-america.com:

extranet:
  hosts:
    web-stag-extranet-01.tld-america.com:

mobile:
  hosts:
    web-stag-mobile-01.tld-america.com:

portals:
  hosts:
    web-stag-portals-01.tld-america.com:

powerbi:
  hosts:
    web-stag-powerbi-01.tld-america.com: