legacy_product_support:
  path: /en/private/product_support/index.ps.php
  host: www.tld-gse.com
  schemes: https

legacy_sales_service_sales:
  path: /en/private/sales_service/sales.php
  host: www.tld-gse.com
  schemes: https

legacy_sales_service_service:
  path: /en/private/sales_service/service.php
  host: www.tld-gse.com
  schemes: https

legacy_sales:
  path: /en/private/sales_service/sales.php
  host: www.tld-gse.com
  schemes: https

legacy_manufacturing_qa:
  path: /en/private/manufacturing/qa/dev.php
  host: www.tld-gse.com
  schemes: https

legacy_manufacturing_env:
  path: /en/private/manufacturing/eng/dev.php
  host: www.tld-gse.com
  schemes: https

legacy_manufacturing_pur:
  path: /en/private/manufacturing/pur/dev.php
  host: www.tld-gse.com
  schemes: https

legacy_parts:
  path: /en/private/parts/parts.php
  host: www.tld-gse.com
  schemes: https

dms:
  path: /index.php
  host: dms.tld-group.com
  schemes: https