<?php

declare(strict_types=1);

namespace App\FileSystem\Zip\Report;

final class ZipReport
{
    public int $requested = 0;
    public int $included = 0;

    /** @var array<int, array{path: string, reason: string}> */
    public array $excluded = [];

    public function exclude(string $path, ZipSkipReason $reason): void
    {
        $this->excluded[] = [
            'path' => $path,
            'reason' => $reason->value,
        ];
    }

    public function addFile(\ZipArchive $zip, string $realPath, string $zipPath): void
    {
        ++$this->requested;

        if (!file_exists($realPath)) {
            $this->exclude($zipPath, ZipSkipReason::FILE_NOT_FOUND);

            return;
        }

        if (!is_file($realPath)) {
            $this->exclude($zipPath, ZipSkipReason::NOT_A_FILE);

            return;
        }

        if (!is_readable($realPath)) {
            $this->exclude($zipPath, ZipSkipReason::PERMISSION_DENIED);

            return;
        }

        $zip->addFile($realPath, $zipPath);
        ++$this->included;
    }

    public function toArray(): array
    {
        return [
            'summary' => [
                'requested' => $this->requested,
                'included' => $this->included,
                'excluded' => \count($this->excluded),
            ],
            'excludedFiles' => $this->excluded,
            'warnings' => [],
            'generatedAt' => (new \DateTimeImmutable())->format(\DATE_ATOM),
        ];
    }

    public function toPlainText(): string
    {
        $generatedAt = (new \DateTimeImmutable())->format(\DATE_RFC2822);
        $excludedCount = \count($this->excluded);

        $out = "ZIP EXPORT REPORT\n";
        $out .= "=================\n\n";
        $out .= "Generated at: $generatedAt\n\n";
        $out .= "SUMMARY\n";
        $out .= "-------\n";
        $out .= "Files requested: {$this->requested}\n";
        $out .= "Files included:  {$this->included}\n";
        $out .= "Files excluded:  $excludedCount\n\n";

        if ($excludedCount > 0) {
            $out .= "EXCLUDED FILES\n";
            $out .= "--------------\n";
            foreach ($this->excluded as $item) {
                $out .= "- {$item['path']}: {$item['reason']}\n";
            }
            $out .= "\n";
        }

        $out .= "This ZIP archive was generated by Alvest Portals.\n";

        return $out;
    }
}
